/* Generated by Yosys 0.29+34 (git sha1 57c9eb70f, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:1.1-46.10" *)
module top(ap_clk, ap_rst, x_var_V, y_var_V, gcd_output_V, gcd_output_V_ap_vld);
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  wire [3:0] _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  wire [3:0] _001_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  wire _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  wire _003_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.46-44.80" *)
  wire _004_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:51.1-57.4" *)
  wire [1:0] _005_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:59.1-65.4" *)
  wire [3:0] _006_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:67.1-73.4" *)
  wire [3:0] _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:83.1-99.4" *)
  wire [1:0] _008_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:60.10-60.68" *)
  wire _009_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:76.10-76.68" *)
  wire _010_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:107.32-107.76" *)
  wire _011_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:60.11-60.38" *)
  wire _012_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:111.35-111.68" *)
  wire _013_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:109.32-109.75" *)
  wire _014_;
  wire _015_;
  wire _016_;
  wire [3:0] _017_;
  wire [3:0] _018_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:69.1-75.4" *)
  wire [5:0] _019_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:103.1-108.4" *)
  wire _020_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:77.1-85.4" *)
  wire [3:0] _021_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:110.1-115.4" *)
  wire [3:0] _022_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:103.1-108.4" *)
  wire [3:0] _023_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:110.1-115.4" *)
  wire [3:0] _024_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:87.1-93.4" *)
  wire [3:0] _025_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:95.1-101.4" *)
  wire [3:0] _026_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:153.1-185.4" *)
  wire [5:0] _027_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:125.1-137.4" *)
  wire [3:0] _028_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:139.1-151.4" *)
  wire [3:0] _029_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:153.1-185.4" *)
  wire [5:0] _030_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:125.1-137.4" *)
  wire [3:0] _031_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:139.1-151.4" *)
  wire [3:0] _032_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:125.1-137.4" *)
  wire [3:0] _033_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:139.1-151.4" *)
  wire [3:0] _034_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:159.18-159.77" *)
  wire _035_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:166.18-166.79" *)
  wire _036_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:82.19-82.78" *)
  wire _037_;
  wire _038_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:203.35-203.83" *)
  wire _039_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:205.33-205.81" *)
  wire _040_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:82.20-82.48" *)
  wire _041_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:211.36-211.70" *)
  wire _042_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:213.36-213.70" *)
  wire _043_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:215.36-215.72" *)
  wire _044_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:207.35-207.78" *)
  wire _045_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:209.33-209.80" *)
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire [3:0] _053_;
  wire [3:0] _054_;
  wire [3:0] _055_;
  wire [3:0] _056_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.12-33.25" *)
  wire _057_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.12-37.25" *)
  wire _058_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.24-44.40" *)
  wire _059_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.18-33.25" *)
  wire _060_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.18-37.25" *)
  wire _061_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.22-44.81" *)
  wire _062_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.22-44.41" *)
  wire _063_;
  wire [3:0] _064_;
  wire _065_;
  wire [3:0] _066_;
  wire _067_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:1.18-1.24" *)
  input ap_clk;
  wire ap_clk;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:1.32-1.38" *)
  input ap_rst;
  wire ap_rst;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:10.15-10.26" *)
  wire [3:0] gcd_output1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:11.14-11.29" *)
  reg [3:0] gcd_output1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:15.15-15.26" *)
  wire [3:0] gcd_output2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:16.14-16.29" *)
  reg [3:0] gcd_output2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:5.22-5.34" *)
  output [3:0] gcd_output_V;
  wire [3:0] gcd_output_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:6.16-6.35" *)
  output gcd_output_V_ap_vld;
  wire gcd_output_V_ap_vld;
  (* fsm_encoding = "none" *)
  (* hdlname = "u1 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:33.41-33.50" *)
  reg [1:0] \u1.ap_CS_fsm  = 2'h1;
  (* hdlname = "u1 ap_CS_fsm_state1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:34.9-34.25" *)
  wire \u1.ap_CS_fsm_state1 ;
  (* hdlname = "u1 ap_CS_fsm_state2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:36.9-36.25" *)
  wire \u1.ap_CS_fsm_state2 ;
  (* hdlname = "u1 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:44.13-44.22" *)
  wire [1:0] \u1.ap_NS_fsm ;
  (* hdlname = "u1 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:24.9-24.15" *)
  wire \u1.ap_clk ;
  (* hdlname = "u1 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:25.9-25.15" *)
  wire \u1.ap_rst ;
  (* hdlname = "u1 gcd_output_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:28.15-28.27" *)
  wire [3:0] \u1.gcd_output_V ;
  (* hdlname = "u1 gcd_output_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:29.10-29.29" *)
  wire \u1.gcd_output_V_ap_vld ;
  (* hdlname = "u1 icmp_ln883_fu_62_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:37.14-37.33" *)
  wire \u1.icmp_ln883_fu_62_p2 ;
  (* hdlname = "u1 icmp_ln887_fu_68_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:41.14-41.33" *)
  wire \u1.icmp_ln887_fu_68_p2 ;
  (* hdlname = "u1 select_ln12_1_fu_94_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:38.14-38.36" *)
  wire [3:0] \u1.select_ln12_1_fu_94_p3 ;
  (* hdlname = "u1 select_ln12_fu_86_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:35.14-35.34" *)
  wire [3:0] \u1.select_ln12_fu_86_p3 ;
  (* hdlname = "u1 sub_ln701_1_fu_80_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:42.14-42.34" *)
  wire [3:0] \u1.sub_ln701_1_fu_80_p2 ;
  (* hdlname = "u1 sub_ln701_fu_74_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:43.14-43.32" *)
  wire [3:0] \u1.sub_ln701_fu_74_p2 ;
  (* hdlname = "u1 x_var_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:26.14-26.21" *)
  wire [3:0] \u1.x_var_V ;
  (* hdlname = "u1 x_var_V_buf_0_reg_43" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:39.13-39.33" *)
  reg [3:0] \u1.x_var_V_buf_0_reg_43 ;
  (* hdlname = "u1 y_var_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:27.14-27.21" *)
  wire [3:0] \u1.y_var_V ;
  (* hdlname = "u1 y_var_V_buf_0_reg_53" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:40.13-40.33" *)
  reg [3:0] \u1.y_var_V_buf_0_reg_53 ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u2 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:39.41-39.50" *)
  reg [5:0] \u2.ap_CS_fsm  = 6'h01;
  (* hdlname = "u2 ap_CS_fsm_state1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:42.9-42.25" *)
  wire \u2.ap_CS_fsm_state1 ;
  (* hdlname = "u2 ap_CS_fsm_state2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:40.9-40.25" *)
  wire \u2.ap_CS_fsm_state2 ;
  (* hdlname = "u2 ap_CS_fsm_state3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:45.9-45.25" *)
  wire \u2.ap_CS_fsm_state3 ;
  (* hdlname = "u2 ap_CS_fsm_state4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:50.9-50.25" *)
  wire \u2.ap_CS_fsm_state4 ;
  (* hdlname = "u2 ap_CS_fsm_state5" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:54.9-54.25" *)
  wire \u2.ap_CS_fsm_state5 ;
  (* hdlname = "u2 ap_CS_fsm_state6" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:58.9-58.25" *)
  wire \u2.ap_CS_fsm_state6 ;
  (* hdlname = "u2 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:62.13-62.22" *)
  wire [5:0] \u2.ap_NS_fsm ;
  (* hdlname = "u2 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:28.9-28.15" *)
  wire \u2.ap_clk ;
  (* hdlname = "u2 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:29.9-29.15" *)
  wire \u2.ap_rst ;
  (* hdlname = "u2 gcd_output_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:32.15-32.27" *)
  wire [3:0] \u2.gcd_output_V ;
  (* hdlname = "u2 gcd_output_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:33.10-33.29" *)
  wire \u2.gcd_output_V_ap_vld ;
  (* hdlname = "u2 grp_fu_80_p0" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:59.13-59.25" *)
  wire [3:0] \u2.grp_fu_80_p0 ;
  (* hdlname = "u2 grp_fu_80_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:60.13-60.25" *)
  wire [3:0] \u2.grp_fu_80_p1 ;
  (* hdlname = "u2 grp_fu_80_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:37.14-37.26" *)
  wire [3:0] \u2.grp_fu_80_p2 ;
  (* hdlname = "u2 icmp_ln883_1_fu_135_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:57.14-57.36" *)
  wire \u2.icmp_ln883_1_fu_135_p2 ;
  (* hdlname = "u2 icmp_ln883_fu_107_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:41.14-41.34" *)
  wire \u2.icmp_ln883_fu_107_p2 ;
  (* hdlname = "u2 icmp_ln887_1_fu_141_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:48.14-48.36" *)
  wire \u2.icmp_ln887_1_fu_141_p2 ;
  (* hdlname = "u2 icmp_ln887_1_reg_191" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:49.13-49.33" *)
  reg \u2.icmp_ln887_1_reg_191 ;
  (* hdlname = "u2 icmp_ln887_fu_113_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:61.14-61.34" *)
  wire \u2.icmp_ln887_fu_113_p2 ;
  (* hdlname = "u2 reg_69" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:38.13-38.19" *)
  reg [3:0] \u2.reg_69 ;
  (* hdlname = "u2 select_ln12_1_fu_127_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:46.14-46.37" *)
  wire [3:0] \u2.select_ln12_1_fu_127_p3 ;
  (* hdlname = "u2 select_ln12_1_reg_180" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:47.13-47.34" *)
  reg [3:0] \u2.select_ln12_1_reg_180 ;
  (* hdlname = "u2 select_ln12_2_fu_152_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:53.14-53.37" *)
  wire [3:0] \u2.select_ln12_2_fu_152_p3 ;
  (* hdlname = "u2 select_ln12_3_fu_145_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:51.14-51.37" *)
  wire [3:0] \u2.select_ln12_3_fu_145_p3 ;
  (* hdlname = "u2 select_ln12_3_reg_196" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:52.13-52.34" *)
  reg [3:0] \u2.select_ln12_3_reg_196 ;
  (* hdlname = "u2 select_ln12_fu_119_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:43.14-43.35" *)
  wire [3:0] \u2.select_ln12_fu_119_p3 ;
  (* hdlname = "u2 select_ln12_reg_171" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:44.13-44.32" *)
  reg [3:0] \u2.select_ln12_reg_171 ;
  (* hdlname = "u2 x_var_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:30.14-30.21" *)
  wire [3:0] \u2.x_var_V ;
  (* hdlname = "u2 x_var_V_buf_0_0_reg_49" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:55.13-55.35" *)
  reg [3:0] \u2.x_var_V_buf_0_0_reg_49 ;
  (* hdlname = "u2 y_var_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:31.14-31.21" *)
  wire [3:0] \u2.y_var_V ;
  (* hdlname = "u2 y_var_V_buf_0_0_reg_59" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:56.13-56.35" *)
  reg [3:0] \u2.y_var_V_buf_0_0_reg_59 ;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:9.9-9.11" *)
  wire v1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:8.8-8.14" *)
  reg v1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:14.9-14.11" *)
  wire v2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:13.8-13.14" *)
  reg v2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:2.15-2.22" *)
  input [3:0] x_var_V;
  wire [3:0] x_var_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:3.15-3.22" *)
  input [3:0] y_var_V;
  wire [3:0] y_var_V;
  always @* if (1'h1) assert(_062_);
  assign _004_ = gcd_output1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.46-44.80" *) gcd_output2_buf;
  assign _009_ = _012_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:68.10-68.68" *) \u1.ap_CS_fsm [1];
  assign _010_ = \u1.icmp_ln883_fu_62_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:76.10-76.68" *) \u1.ap_CS_fsm [1];
  assign _011_ = \u1.x_var_V_buf_0_reg_43  == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:107.32-107.76" *) \u1.y_var_V_buf_0_reg_53 ;
  assign _012_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:60.11-60.38" *) \u1.icmp_ln883_fu_62_p2 ;
  assign _013_ = \u1.icmp_ln887_fu_68_p2  === (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:111.35-111.68" *) 1'h1;
  assign _014_ = \u1.x_var_V_buf_0_reg_43  < (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:109.32-109.75" *) \u1.y_var_V_buf_0_reg_53 ;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:67.1-73.4" *)
  always @(posedge \u1.ap_clk )
    \u1.y_var_V_buf_0_reg_53  <= _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:59.1-65.4" *)
  always @(posedge \u1.ap_clk )
    \u1.x_var_V_buf_0_reg_43  <= _006_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:51.1-57.4" *)
  always @(posedge \u1.ap_clk )
    \u1.ap_CS_fsm  <= _005_;
  assign _008_ = _010_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:89.13-93.16|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:89.17-89.77" *) 2'h1 : 2'h2;
  assign _015_ = \u1.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:84.5-98.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:0.0-0.0" *) 2'h2;
  function [1:0] _081_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:84.5-98.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _081_ = b[1:0];
      2'b1?:
        _081_ = b[3:2];
      default:
        _081_ = a;
    endcase
  endfunction
  assign \u1.ap_NS_fsm  = _081_(2'hx, { 2'h2, _008_ }, { _016_, _015_ });
  assign _016_ = \u1.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:84.5-98.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:0.0-0.0" *) 1'h1;
  assign \u1.gcd_output_V_ap_vld  = _010_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:76.5-80.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:76.9-76.69" *) 1'h1 : 1'h0;
  assign _017_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:70.14-72.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:70.18-70.44" *) \u1.y_var_V  : \u1.y_var_V_buf_0_reg_53 ;
  assign _007_ = _009_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:68.5-72.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:68.9-68.69" *) \u1.select_ln12_1_fu_94_p3  : _017_;
  assign _018_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:62.14-64.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:62.18-62.44" *) \u1.x_var_V  : \u1.x_var_V_buf_0_reg_43 ;
  assign _006_ = _009_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:60.5-64.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:60.9-60.69" *) \u1.select_ln12_fu_86_p3  : _018_;
  assign _005_ = \u1.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:52.5-56.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:52.9-52.23" *) 2'h1 : \u1.ap_NS_fsm ;
  assign \u1.sub_ln701_1_fu_80_p2  = \u1.x_var_V_buf_0_reg_43  - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:115.32-115.75" *) \u1.y_var_V_buf_0_reg_53 ;
  assign \u1.sub_ln701_fu_74_p2  = \u1.y_var_V_buf_0_reg_53  - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:117.30-117.73" *) \u1.x_var_V_buf_0_reg_43 ;
  assign \u1.icmp_ln883_fu_62_p2  = _011_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:107.31-107.91" *) 1'h1 : 1'h0;
  assign \u1.icmp_ln887_fu_68_p2  = _014_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:109.31-109.90" *) 1'h1 : 1'h0;
  assign \u1.select_ln12_1_fu_94_p3  = _013_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:111.34-111.113" *) \u1.sub_ln701_fu_74_p2  : \u1.y_var_V_buf_0_reg_53 ;
  assign \u1.select_ln12_fu_86_p3  = _013_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:18.11-21.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_1.v:113.32-113.113" *) \u1.x_var_V_buf_0_reg_43  : \u1.sub_ln701_1_fu_80_p2 ;
  assign _035_ = \u2.icmp_ln883_fu_107_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:159.18-159.77" *) \u2.ap_CS_fsm [1];
  assign _036_ = \u2.icmp_ln883_1_fu_135_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:166.18-166.79" *) \u2.ap_CS_fsm [2];
  assign _037_ = _041_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:82.19-82.78" *) \u2.ap_CS_fsm [1];
  assign _038_ = | { _052_, _050_ };
  assign _039_ = \u2.select_ln12_fu_119_p3  == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:203.35-203.83" *) \u2.select_ln12_1_fu_127_p3 ;
  assign _040_ = \u2.x_var_V_buf_0_0_reg_49  == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:205.33-205.81" *) \u2.y_var_V_buf_0_0_reg_59 ;
  assign _041_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:82.20-82.48" *) \u2.icmp_ln883_fu_107_p2 ;
  assign _042_ = \u2.icmp_ln887_fu_113_p2  === (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:211.36-211.70" *) 1'h1;
  assign _043_ = \u2.icmp_ln887_1_reg_191  === (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:213.36-213.70" *) 1'h1;
  assign _044_ = \u2.icmp_ln887_1_fu_141_p2  === (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:215.36-215.72" *) 1'h1;
  assign _045_ = \u2.select_ln12_reg_171  < (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:207.35-207.78" *) \u2.select_ln12_1_reg_180 ;
  assign _046_ = \u2.x_var_V_buf_0_0_reg_49  < (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:209.33-209.80" *) \u2.y_var_V_buf_0_0_reg_59 ;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:110.1-115.4" *)
  always @(posedge \u2.ap_clk )
    \u2.select_ln12_reg_171  <= _024_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:110.1-115.4" *)
  always @(posedge \u2.ap_clk )
    \u2.select_ln12_1_reg_180  <= _022_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:103.1-108.4" *)
  always @(posedge \u2.ap_clk )
    \u2.icmp_ln887_1_reg_191  <= _020_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:103.1-108.4" *)
  always @(posedge \u2.ap_clk )
    \u2.select_ln12_3_reg_196  <= _023_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:95.1-101.4" *)
  always @(posedge \u2.ap_clk )
    \u2.y_var_V_buf_0_0_reg_59  <= _026_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:87.1-93.4" *)
  always @(posedge \u2.ap_clk )
    \u2.x_var_V_buf_0_0_reg_49  <= _025_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:77.1-85.4" *)
  always @(posedge \u2.ap_clk )
    \u2.reg_69  <= _021_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:69.1-75.4" *)
  always @(posedge \u2.ap_clk )
    \u2.ap_CS_fsm  <= _019_;
  assign _030_ = _036_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:166.13-170.16|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:166.17-166.80" *) 6'h20 : 6'h08;
  assign _047_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:154.5-184.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:0.0-0.0" *) 3'h4;
  assign _027_ = _035_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:159.13-163.16|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:159.17-159.78" *) 6'h20 : 6'h04;
  assign _048_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:154.5-184.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:0.0-0.0" *) 2'h2;
  function [5:0] _119_;
    input [5:0] a;
    input [29:0] b;
    input [4:0] s;
    (* full_case = 32'd1 *)
    (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:154.5-184.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      5'b????1:
        _119_ = b[5:0];
      5'b???1?:
        _119_ = b[11:6];
      5'b??1??:
        _119_ = b[17:12];
      5'b?1???:
        _119_ = b[23:18];
      5'b1????:
        _119_ = b[29:24];
      default:
        _119_ = a;
    endcase
  endfunction
  assign \u2.ap_NS_fsm  = _119_(6'hxx, { _027_, _030_, 18'h10081 }, { _048_, _047_, _051_, _038_, _049_ });
  assign _049_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:154.5-184.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:0.0-0.0" *) 6'h20;
  assign _050_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:154.5-184.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:0.0-0.0" *) 5'h10;
  assign _051_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:154.5-184.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:0.0-0.0" *) 4'h8;
  assign _052_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:154.5-184.12|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:0.0-0.0" *) 1'h1;
  assign _034_ = \u2.ap_CS_fsm [1] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:146.14-150.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:146.18-146.44" *) \u2.x_var_V_buf_0_0_reg_49  : 4'hx;
  assign _032_ = \u2.ap_CS_fsm [2] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:144.14-150.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:144.18-144.44" *) \u2.y_var_V_buf_0_0_reg_59  : _034_;
  assign _029_ = \u2.ap_CS_fsm [3] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:142.14-150.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:142.18-142.44" *) \u2.select_ln12_reg_171  : _032_;
  assign \u2.grp_fu_80_p1  = \u2.ap_CS_fsm [4] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:140.5-150.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:140.9-140.35" *) \u2.select_ln12_1_reg_180  : _029_;
  assign _033_ = \u2.ap_CS_fsm [1] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:132.14-136.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:132.18-132.44" *) \u2.y_var_V_buf_0_0_reg_59  : 4'hx;
  assign _031_ = \u2.ap_CS_fsm [2] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:130.14-136.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:130.18-130.44" *) \u2.x_var_V_buf_0_0_reg_49  : _033_;
  assign _028_ = \u2.ap_CS_fsm [3] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:128.14-136.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:128.18-128.44" *) \u2.select_ln12_1_reg_180  : _031_;
  assign \u2.grp_fu_80_p0  = \u2.ap_CS_fsm [4] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:126.5-136.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:126.9-126.35" *) \u2.select_ln12_reg_171  : _028_;
  assign \u2.gcd_output_V_ap_vld  = \u2.ap_CS_fsm [5] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:118.5-122.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:118.9-118.35" *) 1'h1 : 1'h0;
  assign _022_ = \u2.ap_CS_fsm [2] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:111.5-114.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:111.9-111.35" *) \u2.select_ln12_1_fu_127_p3  : \u2.select_ln12_1_reg_180 ;
  assign _024_ = \u2.ap_CS_fsm [2] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:111.5-114.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:111.9-111.35" *) \u2.select_ln12_fu_119_p3  : \u2.select_ln12_reg_171 ;
  assign _023_ = \u2.ap_CS_fsm [3] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:104.5-107.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:104.9-104.35" *) \u2.select_ln12_3_fu_145_p3  : \u2.select_ln12_3_reg_196 ;
  assign _020_ = \u2.ap_CS_fsm [3] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:104.5-107.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:104.9-104.35" *) \u2.icmp_ln887_1_fu_141_p2  : \u2.icmp_ln887_1_reg_191 ;
  assign _053_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:98.14-100.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:98.18-98.44" *) \u2.y_var_V  : \u2.y_var_V_buf_0_0_reg_59 ;
  assign _026_ = \u2.ap_CS_fsm [4] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:96.5-100.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:96.9-96.35" *) \u2.select_ln12_3_reg_196  : _053_;
  assign _054_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:90.14-92.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:90.18-90.44" *) \u2.x_var_V  : \u2.x_var_V_buf_0_0_reg_49 ;
  assign _025_ = \u2.ap_CS_fsm [4] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:88.5-92.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:88.9-88.35" *) \u2.select_ln12_2_fu_152_p3  : _054_;
  assign _055_ = _037_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:82.14-84.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:82.18-82.79" *) \u2.grp_fu_80_p2  : \u2.reg_69 ;
  assign _056_ = _035_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:80.14-84.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:80.18-80.79" *) \u2.x_var_V_buf_0_0_reg_49  : _055_;
  assign _021_ = _036_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:78.5-84.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:78.9-78.72" *) \u2.select_ln12_fu_119_p3  : _056_;
  assign _019_ = \u2.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:70.5-74.8|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:70.9-70.23" *) 6'h01 : \u2.ap_NS_fsm ;
  assign \u2.grp_fu_80_p2  = \u2.grp_fu_80_p0  - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:201.24-201.51" *) \u2.grp_fu_80_p1 ;
  assign \u2.icmp_ln883_1_fu_135_p2  = _039_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:203.34-203.98" *) 1'h1 : 1'h0;
  assign \u2.icmp_ln883_fu_107_p2  = _040_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:205.32-205.96" *) 1'h1 : 1'h0;
  assign \u2.icmp_ln887_1_fu_141_p2  = _045_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:207.34-207.93" *) 1'h1 : 1'h0;
  assign \u2.icmp_ln887_fu_113_p2  = _046_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:209.32-209.95" *) 1'h1 : 1'h0;
  assign \u2.select_ln12_1_fu_127_p3  = _042_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:211.35-211.105" *) \u2.reg_69  : \u2.y_var_V_buf_0_0_reg_59 ;
  assign \u2.select_ln12_2_fu_152_p3  = _043_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:213.35-213.108" *) \u2.select_ln12_reg_171  : \u2.grp_fu_80_p2 ;
  assign \u2.select_ln12_3_fu_145_p3  = _044_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:215.35-215.112" *) \u2.grp_fu_80_p2  : \u2.select_ln12_1_reg_180 ;
  assign \u2.select_ln12_fu_119_p3  = _042_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:23.9-26.58|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/gcd_4.v:217.33-217.109" *) \u2.x_var_V_buf_0_0_reg_49  : \u2.grp_fu_80_p2 ;
  assign _057_ = v1 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.12-33.25" *) _060_;
  assign _058_ = v2 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.12-37.25" *) _061_;
  assign _059_ = v1_buf && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.24-44.40" *) v2_buf;
  assign _060_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.18-33.25" *) v1_buf;
  assign _061_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.18-37.25" *) v2_buf;
  assign _062_ = _063_ || (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.22-44.81" *) _004_;
  assign _063_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:44.22-44.41" *) _059_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    v1_buf <= _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    gcd_output1_buf <= _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    v2_buf <= _003_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    gcd_output2_buf <= _001_;
  assign _064_ = _058_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.12-37.25|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.8-40.11" *) gcd_output2 : gcd_output2_buf;
  assign _001_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.6-41.9" *) gcd_output2_buf : _064_;
  assign _065_ = _058_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.12-37.25|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:37.8-40.11" *) 1'h1 : v2_buf;
  assign _003_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.6-41.9" *) 1'h0 : _065_;
  assign _066_ = _057_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.12-33.25|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.8-36.11" *) gcd_output1 : gcd_output1_buf;
  assign _000_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.6-41.9" *) gcd_output1_buf : _066_;
  assign _067_ = _057_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.12-33.25|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:33.8-36.11" *) 1'h1 : v1_buf;
  assign _002_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/gcd_wrapper_1_4/top.v:29.6-41.9" *) 1'h0 : _067_;
  assign \u2.ap_CS_fsm_state1  = \u2.ap_CS_fsm [0];
  assign \u2.ap_CS_fsm_state2  = \u2.ap_CS_fsm [1];
  assign \u2.ap_CS_fsm_state3  = \u2.ap_CS_fsm [2];
  assign \u2.ap_CS_fsm_state4  = \u2.ap_CS_fsm [3];
  assign \u2.ap_CS_fsm_state5  = \u2.ap_CS_fsm [4];
  assign \u2.ap_CS_fsm_state6  = \u2.ap_CS_fsm [5];
  assign \u2.gcd_output_V  = \u2.reg_69 ;
  assign \u2.ap_clk  = ap_clk;
  assign \u2.ap_rst  = ap_rst;
  assign gcd_output2 = \u2.gcd_output_V ;
  assign v2 = \u2.gcd_output_V_ap_vld ;
  assign \u2.x_var_V  = x_var_V;
  assign \u2.y_var_V  = y_var_V;
  assign \u1.ap_CS_fsm_state1  = \u1.ap_CS_fsm [0];
  assign \u1.ap_CS_fsm_state2  = \u1.ap_CS_fsm [1];
  assign \u1.gcd_output_V  = \u1.x_var_V_buf_0_reg_43 ;
  assign \u1.ap_clk  = ap_clk;
  assign \u1.ap_rst  = ap_rst;
  assign gcd_output1 = \u1.gcd_output_V ;
  assign v1 = \u1.gcd_output_V_ap_vld ;
  assign \u1.x_var_V  = x_var_V;
  assign \u1.y_var_V  = y_var_V;
endmodule
