/* Generated by Yosys 0.29+34 (git sha1 57c9eb70f, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:1.1-46.10" *)
module top(ap_clk, ap_rst, nonce_input_V, in_port_V, output_V, output_V_ap_vld);
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  wire [3:0] _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  wire [3:0] _001_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  wire _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  wire _003_;
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] _004_;
  (* unused_bits = "0 1 2 3" *)
  wire [3:0] _005_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.46-44.72" *)
  wire _006_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  wire [3:0] _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  wire [3:0] _008_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:103.1-109.4" *)
  wire _009_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:111.1-119.4" *)
  wire _010_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  wire _011_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  wire [3:0] _012_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:141.10-141.114" *)
  wire _013_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [3:0] _014_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:128.1-132.4" *)
  wire [3:0] _015_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [1:0] _016_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:104.1-110.4" *)
  wire [2:0] _017_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [1:0] _018_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire _019_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [3:0] _020_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [3:0] _021_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [3:0] _022_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [3:0] _023_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [2:0] _024_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire _025_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  wire [1:0] _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.12-33.25" *)
  wire _030_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.12-37.25" *)
  wire _031_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.24-44.40" *)
  wire _032_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.18-33.25" *)
  wire _033_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.18-37.25" *)
  wire _034_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.22-44.73" *)
  wire _035_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.22-44.41" *)
  wire _036_;
  wire [3:0] _037_;
  wire _038_;
  wire [3:0] _039_;
  wire _040_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:1.18-1.24" *)
  input ap_clk;
  wire ap_clk;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:1.32-1.38" *)
  input ap_rst;
  wire ap_rst;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:3.15-3.24" *)
  input [15:0] in_port_V;
  wire [15:0] in_port_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:2.14-2.27" *)
  input [5:0] nonce_input_V;
  wire [5:0] nonce_input_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:10.15-10.22" *)
  wire [3:0] output1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:11.14-11.25" *)
  reg [3:0] output1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:15.15-15.22" *)
  wire [3:0] output2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:16.14-16.25" *)
  reg [3:0] output2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:5.22-5.30" *)
  output [3:0] output_V;
  wire [3:0] output_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:6.16-6.31" *)
  output output_V_ap_vld;
  wire output_V_ap_vld;
  (* hdlname = "u1 add_ln214_1_fu_209_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:58.20-58.41" *)
  wire [3:0] \u1.add_ln214_1_fu_209_p2 ;
  (* hdlname = "u1 add_ln214_2_fu_215_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:60.20-60.41" *)
  wire [3:0] \u1.add_ln214_2_fu_215_p2 ;
  (* hdlname = "u1 add_ln214_3_fu_293_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:74.20-74.41" *)
  wire [3:0] \u1.add_ln214_3_fu_293_p2 ;
  (* hdlname = "u1 add_ln214_4_fu_299_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:75.20-75.41" *)
  wire [3:0] \u1.add_ln214_4_fu_299_p2 ;
  (* hdlname = "u1 add_ln214_5_fu_380_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:86.20-86.41" *)
  wire [3:0] \u1.add_ln214_5_fu_380_p2 ;
  (* hdlname = "u1 add_ln214_6_fu_390_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:87.20-87.41" *)
  wire [3:0] \u1.add_ln214_6_fu_390_p2 ;
  (* hdlname = "u1 add_ln214_fu_145_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:54.20-54.39" *)
  wire [3:0] \u1.add_ln214_fu_145_p2 ;
  (* hdlname = "u1 add_ln700_1_fu_239_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:66.14-66.35" *)
  wire [3:0] \u1.add_ln700_1_fu_239_p2 ;
  (* hdlname = "u1 add_ln700_2_fu_245_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:32.20-32.41" *)
  wire [3:0] \u1.add_ln700_2_fu_245_p2 ;
  (* hdlname = "u1 add_ln700_2_reg_416" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:33.19-33.38" *)
  reg [3:0] \u1.add_ln700_2_reg_416 ;
  (* hdlname = "u1 add_ln700_3_fu_317_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:81.14-81.35" *)
  wire [3:0] \u1.add_ln700_3_fu_317_p2 ;
  (* hdlname = "u1 add_ln700_4_fu_323_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:80.14-80.35" *)
  wire [3:0] \u1.add_ln700_4_fu_323_p2 ;
  (* hdlname = "u1 add_ln700_5_fu_329_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:39.20-39.41" *)
  wire [3:0] \u1.add_ln700_5_fu_329_p2 ;
  (* hdlname = "u1 add_ln700_5_reg_422" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:40.19-40.38" *)
  reg [3:0] \u1.add_ln700_5_reg_422 ;
  (* hdlname = "u1 add_ln700_6_fu_374_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:91.14-91.35" *)
  wire [3:0] \u1.add_ln700_6_fu_374_p2 ;
  (* hdlname = "u1 add_ln700_7_fu_401_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:90.14-90.35" *)
  wire [3:0] \u1.add_ln700_7_fu_401_p2 ;
  (* hdlname = "u1 add_ln700_fu_233_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:67.14-67.33" *)
  wire [3:0] \u1.add_ln700_fu_233_p2 ;
  (* hdlname = "u1 and_ln214_1_fu_357_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:82.14-82.35" *)
  wire [3:0] \u1.and_ln214_1_fu_357_p3 ;
  (* hdlname = "u1 and_ln_fu_183_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:52.14-52.30" *)
  wire [3:0] \u1.and_ln_fu_183_p3 ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u1 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:34.41-34.50" *)
  reg \u1.ap_CS_fsm  = 1'h1;
  (* hdlname = "u1 ap_CS_fsm_pp0_stage0" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:35.9-35.29" *)
  wire \u1.ap_CS_fsm_pp0_stage0 ;
  (* hdlname = "u1 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:92.13-92.22" *)
  wire \u1.ap_NS_fsm ;
  (* hdlname = "u1 ap_block_pp0_stage0" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:46.9-46.28" *)
  wire \u1.ap_block_pp0_stage0 ;
  (* hdlname = "u1 ap_block_pp0_stage0_01001" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:45.9-45.34" *)
  wire \u1.ap_block_pp0_stage0_01001 ;
  (* hdlname = "u1 ap_block_pp0_stage0_11001" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:38.9-38.34" *)
  wire \u1.ap_block_pp0_stage0_11001 ;
  (* hdlname = "u1 ap_block_pp0_stage0_subdone" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:44.9-44.36" *)
  wire \u1.ap_block_pp0_stage0_subdone ;
  (* hdlname = "u1 ap_block_state1_pp0_stage0_iter0" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:36.9-36.41" *)
  wire \u1.ap_block_state1_pp0_stage0_iter0 ;
  (* hdlname = "u1 ap_block_state2_pp0_stage0_iter1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:37.9-37.41" *)
  wire \u1.ap_block_state2_pp0_stage0_iter1 ;
  (* hdlname = "u1 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:23.9-23.15" *)
  wire \u1.ap_clk ;
  (* hdlname = "u1 ap_enable_pp0" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:95.9-95.22" *)
  wire \u1.ap_enable_pp0 ;
  (* hdlname = "u1 ap_enable_reg_pp0_iter1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:43.8-43.31" *)
  reg \u1.ap_enable_reg_pp0_iter1  = 1'h0;
  (* hdlname = "u1 ap_idle_pp0" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:94.8-94.19" *)
  wire \u1.ap_idle_pp0 ;
  (* hdlname = "u1 ap_reset_idle_pp0" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:93.9-93.26" *)
  wire \u1.ap_reset_idle_pp0 ;
  (* hdlname = "u1 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:24.9-24.15" *)
  wire \u1.ap_rst ;
  (* hdlname = "u1 in_port_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:26.15-26.24" *)
  wire [15:0] \u1.in_port_V ;
  (* hdlname = "u1 mul_ln700_10_fu_385_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:89.14-89.36" *)
  wire [3:0] \u1.mul_ln700_10_fu_385_p2 ;
  (* hdlname = "u1 mul_ln700_11_fu_396_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:88.14-88.36" *)
  wire [3:0] \u1.mul_ln700_11_fu_396_p2 ;
  (* hdlname = "u1 mul_ln700_1_fu_203_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:63.14-63.35" *)
  wire [3:0] \u1.mul_ln700_1_fu_203_p2 ;
  (* hdlname = "u1 mul_ln700_2_fu_221_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:65.14-65.35" *)
  wire [3:0] \u1.mul_ln700_2_fu_221_p2 ;
  (* hdlname = "u1 mul_ln700_3_fu_227_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:64.14-64.35" *)
  wire [3:0] \u1.mul_ln700_3_fu_227_p2 ;
  (* hdlname = "u1 mul_ln700_4_fu_269_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:76.14-76.35" *)
  wire [3:0] \u1.mul_ln700_4_fu_269_p2 ;
  (* hdlname = "u1 mul_ln700_5_fu_279_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:73.14-73.35" *)
  wire [1:0] \u1.mul_ln700_5_fu_279_p2 ;
  (* hdlname = "u1 mul_ln700_6_fu_305_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:79.14-79.35" *)
  wire [3:0] \u1.mul_ln700_6_fu_305_p2 ;
  (* hdlname = "u1 mul_ln700_7_fu_311_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:78.14-78.35" *)
  wire [3:0] \u1.mul_ln700_7_fu_311_p2 ;
  (* hdlname = "u1 mul_ln700_8_fu_353_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:85.14-85.35" *)
  wire [3:0] \u1.mul_ln700_8_fu_353_p2 ;
  (* hdlname = "u1 mul_ln700_9_fu_369_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:84.14-84.35" *)
  wire [3:0] \u1.mul_ln700_9_fu_369_p2 ;
  (* hdlname = "u1 mul_ln700_fu_197_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:62.14-62.33" *)
  wire [3:0] \u1.mul_ln700_fu_197_p2 ;
  (* hdlname = "u1 nonce_input_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:25.14-25.27" *)
  wire [5:0] \u1.nonce_input_V ;
  (* hdlname = "u1 out_port_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:27.15-27.25" *)
  wire [7:0] \u1.out_port_V ;
  (* hdlname = "u1 out_port_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:28.10-28.27" *)
  wire \u1.out_port_V_ap_vld ;
  (* hdlname = "u1 shl_ln1_fu_285_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:77.14-77.31" *)
  wire [3:0] \u1.shl_ln1_fu_285_p3 ;
  (* hdlname = "u1 shl_ln214_1_fu_165_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:70.14-70.35" *)
  wire [3:0] \u1.shl_ln214_1_fu_165_p3 ;
  (* hdlname = "u1 shl_ln214_2_fu_255_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:69.14-69.35" *)
  wire [3:0] \u1.shl_ln214_2_fu_255_p3 ;
  (* hdlname = "u1 shl_ln_fu_137_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:48.14-48.30" *)
  wire [3:0] \u1.shl_ln_fu_137_p3 ;
  (* hdlname = "u1 sub_ln214_1_fu_263_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:71.20-71.41" *)
  wire [3:0] \u1.sub_ln214_1_fu_263_p2 ;
  (* hdlname = "u1 sub_ln214_2_fu_364_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:83.20-83.41" *)
  wire [3:0] \u1.sub_ln214_2_fu_364_p2 ;
  (* hdlname = "u1 sub_ln214_fu_191_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:56.20-56.39" *)
  wire [3:0] \u1.sub_ln214_fu_191_p2 ;
  (* hdlname = "u1 tmp_2_fu_173_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:51.20-51.35" *)
  wire [1:0] \u1.tmp_2_fu_173_p4 ;
  (* hdlname = "u1 tmp_reg_435" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:42.13-42.24" *)
  reg \u1.tmp_reg_435 ;
  (* hdlname = "u1 trunc_ln1503_1_fu_99_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:61.20-61.43" *)
  wire [3:0] \u1.trunc_ln1503_1_fu_99_p4 ;
  (* hdlname = "u1 trunc_ln1503_2_fu_109_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:55.20-55.44" *)
  wire [3:0] \u1.trunc_ln1503_2_fu_109_p4 ;
  (* hdlname = "u1 trunc_ln1503_3_fu_119_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:59.20-59.44" *)
  wire [3:0] \u1.trunc_ln1503_3_fu_119_p4 ;
  (* hdlname = "u1 trunc_ln1503_4_fu_129_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:49.14-49.38" *)
  wire [3:0] \u1.trunc_ln1503_4_fu_129_p1 ;
  (* hdlname = "u1 trunc_ln1503_5_fu_151_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:53.14-53.38" *)
  wire [3:0] \u1.trunc_ln1503_5_fu_151_p4 ;
  (* hdlname = "u1 trunc_ln1503_6_reg_428" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:41.19-41.41" *)
  reg [3:0] \u1.trunc_ln1503_6_reg_428 ;
  (* hdlname = "u1 trunc_ln1503_fu_95_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:57.20-57.41" *)
  wire [3:0] \u1.trunc_ln1503_fu_95_p1 ;
  (* hdlname = "u1 trunc_ln214_1_fu_161_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:50.14-50.37" *)
  wire [2:0] \u1.trunc_ln214_1_fu_161_p1 ;
  (* hdlname = "u1 trunc_ln214_2_fu_251_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:68.14-68.37" *)
  wire \u1.trunc_ln214_2_fu_251_p1 ;
  (* hdlname = "u1 trunc_ln214_fu_133_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:47.14-47.35" *)
  wire [1:0] \u1.trunc_ln214_fu_133_p1 ;
  (* hdlname = "u1 trunc_ln700_fu_275_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:72.20-72.41" *)
  wire [1:0] \u1.trunc_ln700_fu_275_p1 ;
  (* hdlname = "u2 add_ln214_1_fu_201_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:67.20-67.41" *)
  wire [3:0] \u2.add_ln214_1_fu_201_p2 ;
  (* hdlname = "u2 add_ln214_2_fu_207_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:68.20-68.41" *)
  wire [3:0] \u2.add_ln214_2_fu_207_p2 ;
  (* hdlname = "u2 add_ln214_3_fu_306_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:79.20-79.41" *)
  wire [3:0] \u2.add_ln214_3_fu_306_p2 ;
  (* hdlname = "u2 add_ln214_4_fu_312_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:80.20-80.41" *)
  wire [3:0] \u2.add_ln214_4_fu_312_p2 ;
  (* hdlname = "u2 add_ln214_5_fu_372_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:91.20-91.41" *)
  wire [3:0] \u2.add_ln214_5_fu_372_p2 ;
  (* hdlname = "u2 add_ln214_6_fu_382_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:92.20-92.41" *)
  wire [3:0] \u2.add_ln214_6_fu_382_p2 ;
  (* hdlname = "u2 add_ln214_fu_145_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:64.20-64.39" *)
  wire [3:0] \u2.add_ln214_fu_145_p2 ;
  (* hdlname = "u2 add_ln700_1_fu_231_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:73.14-73.35" *)
  wire [3:0] \u2.add_ln700_1_fu_231_p2 ;
  (* hdlname = "u2 add_ln700_2_fu_237_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:48.20-48.41" *)
  wire [3:0] \u2.add_ln700_2_fu_237_p2 ;
  (* hdlname = "u2 add_ln700_2_reg_438" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:49.19-49.38" *)
  reg [3:0] \u2.add_ln700_2_reg_438 ;
  (* hdlname = "u2 add_ln700_3_fu_327_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:86.14-86.35" *)
  wire [3:0] \u2.add_ln700_3_fu_327_p2 ;
  (* hdlname = "u2 add_ln700_4_fu_333_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:85.14-85.35" *)
  wire [3:0] \u2.add_ln700_4_fu_333_p2 ;
  (* hdlname = "u2 add_ln700_5_fu_339_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:56.20-56.41" *)
  wire [3:0] \u2.add_ln700_5_fu_339_p2 ;
  (* hdlname = "u2 add_ln700_5_reg_466" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:57.19-57.38" *)
  reg [3:0] \u2.add_ln700_5_reg_466 ;
  (* hdlname = "u2 add_ln700_6_fu_366_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:96.14-96.35" *)
  wire [3:0] \u2.add_ln700_6_fu_366_p2 ;
  (* hdlname = "u2 add_ln700_7_fu_393_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:95.14-95.35" *)
  wire [3:0] \u2.add_ln700_7_fu_393_p2 ;
  (* hdlname = "u2 add_ln700_fu_225_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:74.14-74.33" *)
  wire [3:0] \u2.add_ln700_fu_225_p2 ;
  (* hdlname = "u2 and_ln214_1_fu_349_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:87.14-87.35" *)
  wire [3:0] \u2.and_ln214_1_fu_349_p3 ;
  (* hdlname = "u2 and_ln_fu_175_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:46.14-46.30" *)
  wire [3:0] \u2.and_ln_fu_175_p3 ;
  (* hdlname = "u2 and_ln_reg_433" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:47.13-47.27" *)
  reg [3:0] \u2.and_ln_reg_433 ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u2 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:36.41-36.50" *)
  reg [2:0] \u2.ap_CS_fsm  = 3'h1;
  (* hdlname = "u2 ap_CS_fsm_state1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:37.9-37.25" *)
  wire \u2.ap_CS_fsm_state1 ;
  (* hdlname = "u2 ap_CS_fsm_state2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:58.9-58.25" *)
  wire \u2.ap_CS_fsm_state2 ;
  (* hdlname = "u2 ap_CS_fsm_state3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:59.9-59.25" *)
  wire \u2.ap_CS_fsm_state3 ;
  (* hdlname = "u2 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:97.13-97.22" *)
  wire [2:0] \u2.ap_NS_fsm ;
  (* hdlname = "u2 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:25.9-25.15" *)
  wire \u2.ap_clk ;
  (* hdlname = "u2 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:26.9-26.15" *)
  wire \u2.ap_rst ;
  (* hdlname = "u2 in_port_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:28.15-28.24" *)
  wire [15:0] \u2.in_port_V ;
  (* hdlname = "u2 mul_ln700_10_fu_377_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:94.14-94.36" *)
  wire [3:0] \u2.mul_ln700_10_fu_377_p2 ;
  (* hdlname = "u2 mul_ln700_11_fu_388_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:93.14-93.36" *)
  wire [3:0] \u2.mul_ln700_11_fu_388_p2 ;
  (* hdlname = "u2 mul_ln700_1_fu_195_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:70.14-70.35" *)
  wire [3:0] \u2.mul_ln700_1_fu_195_p2 ;
  (* hdlname = "u2 mul_ln700_2_fu_213_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:72.14-72.35" *)
  wire [3:0] \u2.mul_ln700_2_fu_213_p2 ;
  (* hdlname = "u2 mul_ln700_3_fu_219_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:71.14-71.35" *)
  wire [3:0] \u2.mul_ln700_3_fu_219_p2 ;
  (* hdlname = "u2 mul_ln700_4_fu_289_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:81.14-81.35" *)
  wire [3:0] \u2.mul_ln700_4_fu_289_p2 ;
  (* hdlname = "u2 mul_ln700_5_fu_294_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:78.14-78.35" *)
  wire [1:0] \u2.mul_ln700_5_fu_294_p2 ;
  (* hdlname = "u2 mul_ln700_6_fu_317_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:84.14-84.35" *)
  wire [3:0] \u2.mul_ln700_6_fu_317_p2 ;
  (* hdlname = "u2 mul_ln700_7_fu_322_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:83.14-83.35" *)
  wire [3:0] \u2.mul_ln700_7_fu_322_p2 ;
  (* hdlname = "u2 mul_ln700_8_fu_345_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:90.14-90.35" *)
  wire [3:0] \u2.mul_ln700_8_fu_345_p2 ;
  (* hdlname = "u2 mul_ln700_9_fu_361_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:89.14-89.35" *)
  wire [3:0] \u2.mul_ln700_9_fu_361_p2 ;
  (* hdlname = "u2 mul_ln700_fu_189_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:69.14-69.33" *)
  wire [3:0] \u2.mul_ln700_fu_189_p2 ;
  (* hdlname = "u2 nonce_input_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:27.14-27.27" *)
  wire [5:0] \u2.nonce_input_V ;
  (* hdlname = "u2 out_port_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:29.15-29.25" *)
  wire [7:0] \u2.out_port_V ;
  (* hdlname = "u2 out_port_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:30.10-30.27" *)
  wire \u2.out_port_V_ap_vld ;
  (* hdlname = "u2 shl_ln1_fu_298_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:82.14-82.31" *)
  wire [3:0] \u2.shl_ln1_fu_298_p3 ;
  (* hdlname = "u2 shl_ln214_1_fu_269_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:76.14-76.35" *)
  wire [3:0] \u2.shl_ln214_1_fu_269_p3 ;
  (* hdlname = "u2 shl_ln214_2_fu_276_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:75.14-75.35" *)
  wire [3:0] \u2.shl_ln214_2_fu_276_p3 ;
  (* hdlname = "u2 shl_ln_fu_137_p3" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:61.14-61.30" *)
  wire [3:0] \u2.shl_ln_fu_137_p3 ;
  (* hdlname = "u2 sub_ln214_1_fu_283_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:77.20-77.41" *)
  wire [3:0] \u2.sub_ln214_1_fu_283_p2 ;
  (* hdlname = "u2 sub_ln214_2_fu_356_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:88.20-88.41" *)
  wire [3:0] \u2.sub_ln214_2_fu_356_p2 ;
  (* hdlname = "u2 sub_ln214_fu_183_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:65.20-65.39" *)
  wire [3:0] \u2.sub_ln214_fu_183_p2 ;
  (* hdlname = "u2 tmp_2_fu_165_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:44.20-44.35" *)
  wire [1:0] \u2.tmp_2_fu_165_p4 ;
  (* hdlname = "u2 tmp_2_reg_428" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:45.19-45.32" *)
  reg [1:0] \u2.tmp_2_reg_428 ;
  (* hdlname = "u2 tmp_reg_461" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:55.13-55.24" *)
  reg \u2.tmp_reg_461 ;
  (* hdlname = "u2 trunc_ln1503_1_fu_99_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:34.20-34.43" *)
  wire [3:0] \u2.trunc_ln1503_1_fu_99_p4 ;
  (* hdlname = "u2 trunc_ln1503_1_reg_408" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:35.19-35.41" *)
  reg [3:0] \u2.trunc_ln1503_1_reg_408 ;
  (* hdlname = "u2 trunc_ln1503_2_fu_109_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:38.20-38.44" *)
  wire [3:0] \u2.trunc_ln1503_2_fu_109_p4 ;
  (* hdlname = "u2 trunc_ln1503_2_reg_413" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:39.19-39.41" *)
  reg [3:0] \u2.trunc_ln1503_2_reg_413 ;
  (* hdlname = "u2 trunc_ln1503_3_fu_119_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:40.20-40.44" *)
  wire [3:0] \u2.trunc_ln1503_3_fu_119_p4 ;
  (* hdlname = "u2 trunc_ln1503_3_reg_418" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:41.19-41.41" *)
  reg [3:0] \u2.trunc_ln1503_3_reg_418 ;
  (* hdlname = "u2 trunc_ln1503_4_fu_129_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:62.14-62.38" *)
  wire [3:0] \u2.trunc_ln1503_4_fu_129_p1 ;
  (* hdlname = "u2 trunc_ln1503_5_fu_151_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:63.14-63.38" *)
  wire [3:0] \u2.trunc_ln1503_5_fu_151_p4 ;
  (* hdlname = "u2 trunc_ln1503_6_reg_454" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:54.19-54.41" *)
  reg [3:0] \u2.trunc_ln1503_6_reg_454 ;
  (* hdlname = "u2 trunc_ln1503_fu_95_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:66.20-66.41" *)
  wire [3:0] \u2.trunc_ln1503_fu_95_p1 ;
  (* hdlname = "u2 trunc_ln214_1_fu_161_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:42.14-42.37" *)
  wire [2:0] \u2.trunc_ln214_1_fu_161_p1 ;
  (* hdlname = "u2 trunc_ln214_1_reg_423" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:43.13-43.34" *)
  reg [2:0] \u2.trunc_ln214_1_reg_423 ;
  (* hdlname = "u2 trunc_ln214_2_fu_243_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:50.14-50.37" *)
  wire \u2.trunc_ln214_2_fu_243_p1 ;
  (* hdlname = "u2 trunc_ln214_2_reg_444" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:51.13-51.34" *)
  reg \u2.trunc_ln214_2_reg_444 ;
  (* hdlname = "u2 trunc_ln214_fu_133_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:60.14-60.35" *)
  wire [1:0] \u2.trunc_ln214_fu_133_p1 ;
  (* hdlname = "u2 trunc_ln700_fu_247_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:52.20-52.41" *)
  wire [1:0] \u2.trunc_ln700_fu_247_p1 ;
  (* hdlname = "u2 trunc_ln700_reg_449" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:53.19-53.38" *)
  reg [1:0] \u2.trunc_ln700_reg_449 ;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:9.9-9.11" *)
  wire v1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:8.8-8.14" *)
  reg v1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:14.9-14.11" *)
  wire v2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:13.8-13.14" *)
  reg v2_buf;
  always @* if (1'h1) assert(_035_);
  assign _006_ = output1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.46-44.72" *) output2_buf;
  assign \u1.add_ln214_1_fu_209_p2  = $signed(4'h7) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:159.33-159.77" *) $signed(\u1.add_ln214_fu_145_p2 );
  assign \u1.add_ln214_2_fu_215_p2  = $signed(2'h2) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:161.33-161.78" *) $signed(\u1.sub_ln214_fu_191_p2 );
  assign \u1.add_ln214_3_fu_293_p2  = $signed(4'h7) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:163.33-163.79" *) $signed(\u1.sub_ln214_1_fu_263_p2 );
  assign \u1.add_ln214_4_fu_299_p2  = $signed(2'h2) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:165.33-165.75" *) $signed({ \u1.nonce_input_V [2:1], 2'h0 });
  assign \u1.add_ln214_5_fu_380_p2  = $signed(1'h1) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:167.33-167.81" *) $signed(\u1.trunc_ln1503_6_reg_428 );
  assign \u1.add_ln214_6_fu_390_p2  = $signed(1'h1) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:169.33-169.80" *) $signed(\u1.sub_ln214_2_fu_364_p2 );
  assign \u1.add_ln214_fu_145_p2  = { \u1.nonce_input_V [1:0], 2'h0 } + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:171.31-171.74" *) \u1.nonce_input_V [3:0];
  assign \u1.add_ln700_1_fu_239_p2  = \u1.mul_ln700_3_fu_227_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:173.33-173.78" *) \u1.mul_ln700_2_fu_221_p2 ;
  assign \u1.add_ln700_2_fu_245_p2  = \u1.add_ln700_1_fu_239_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:175.33-175.76" *) \u1.add_ln700_fu_233_p2 ;
  assign \u1.add_ln700_3_fu_317_p2  = \u1.mul_ln700_4_fu_269_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:177.33-177.74" *) { \u1.mul_ln700_5_fu_279_p2 , 2'h0 };
  assign \u1.add_ln700_4_fu_323_p2  = \u1.mul_ln700_7_fu_311_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:179.33-179.78" *) \u1.mul_ln700_6_fu_305_p2 ;
  assign \u1.add_ln700_5_fu_329_p2  = \u1.add_ln700_4_fu_323_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:181.33-181.78" *) \u1.add_ln700_3_fu_317_p2 ;
  assign \u1.add_ln700_6_fu_374_p2  = \u1.mul_ln700_9_fu_369_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:183.33-183.78" *) \u1.mul_ln700_8_fu_353_p2 ;
  assign \u1.add_ln700_7_fu_401_p2  = \u1.mul_ln700_11_fu_396_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:185.33-185.80" *) \u1.mul_ln700_10_fu_385_p2 ;
  assign \u1.add_ln700_fu_233_p2  = \u1.mul_ln700_fu_197_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:187.31-187.74" *) \u1.mul_ln700_1_fu_203_p2 ;
  assign _013_ = \u1.ap_enable_reg_pp0_iter1  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:141.10-141.114" *) \u1.ap_CS_fsm ;
  assign \u1.mul_ln700_10_fu_385_p2  = $signed(\u1.add_ln214_5_fu_380_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:209.34-209.95" *) $signed(\u1.add_ln700_2_reg_416 );
  assign \u1.mul_ln700_11_fu_396_p2  = $signed(\u1.add_ln214_6_fu_390_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:211.34-211.95" *) $signed(\u1.add_ln700_5_reg_422 );
  assign \u1.mul_ln700_1_fu_203_p2  = $signed(\u1.sub_ln214_fu_191_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:213.33-213.94" *) $signed(\u1.in_port_V [3:0]);
  assign \u1.mul_ln700_2_fu_221_p2  = $signed(\u1.add_ln214_1_fu_209_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:215.33-215.99" *) $signed(\u1.in_port_V [15:12]);
  assign \u1.mul_ln700_3_fu_227_p2  = $signed(\u1.add_ln214_2_fu_215_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:217.33-217.98" *) $signed(\u1.in_port_V [7:4]);
  assign \u1.mul_ln700_4_fu_269_p2  = $signed(\u1.sub_ln214_1_fu_263_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:219.33-219.99" *) $signed(\u1.in_port_V [11:8]);
  assign \u1.mul_ln700_5_fu_279_p2  = $signed(\u1.in_port_V [1:0]) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:221.33-221.90" *) $signed(\u1.nonce_input_V [2:1]);
  assign \u1.mul_ln700_6_fu_305_p2  = $signed(\u1.add_ln214_3_fu_293_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:223.33-223.99" *) $signed(\u1.in_port_V [15:12]);
  assign \u1.mul_ln700_7_fu_311_p2  = $signed(\u1.add_ln214_4_fu_299_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:225.33-225.98" *) $signed(\u1.in_port_V [7:4]);
  assign \u1.mul_ln700_8_fu_353_p2  = $signed(\u1.trunc_ln1503_6_reg_428 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:227.33-227.95" *) $signed(\u1.add_ln700_2_reg_416 );
  assign \u1.mul_ln700_9_fu_369_p2  = $signed(\u1.sub_ln214_2_fu_364_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:229.33-229.94" *) $signed(\u1.add_ln700_5_reg_422 );
  assign \u1.mul_ln700_fu_197_p2  = $signed(\u1.add_ln214_fu_145_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:231.31-231.95" *) $signed(\u1.in_port_V [11:8]);
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  always @(posedge \u1.ap_clk )
    \u1.add_ln700_2_reg_416  <= _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  always @(posedge \u1.ap_clk )
    \u1.add_ln700_5_reg_422  <= _008_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  always @(posedge \u1.ap_clk )
    \u1.trunc_ln1503_6_reg_428  <= _012_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:121.1-128.4" *)
  always @(posedge \u1.ap_clk )
    \u1.tmp_reg_435  <= _011_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:111.1-119.4" *)
  always @(posedge \u1.ap_clk )
    \u1.ap_enable_reg_pp0_iter1  <= _010_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:103.1-109.4" *)
  always @(posedge \u1.ap_clk )
    \u1.ap_CS_fsm  <= _009_;
  assign \u1.ap_NS_fsm  = \u1.ap_CS_fsm  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:149.5-156.12|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:0.0-0.0" *) 1'h1 : 1'hx;
  assign \u1.out_port_V_ap_vld  = _013_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:141.5-145.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:141.9-141.115" *) 1'h1 : 1'h0;
  assign _011_ = \u1.ap_CS_fsm  ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.5-127.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.9-122.79" *) \u1.nonce_input_V [2] : \u1.tmp_reg_435 ;
  assign _012_ = \u1.ap_CS_fsm  ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.5-127.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.9-122.79" *) \u1.nonce_input_V [5:2] : \u1.trunc_ln1503_6_reg_428 ;
  assign _008_ = \u1.ap_CS_fsm  ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.5-127.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.9-122.79" *) \u1.add_ln700_5_fu_329_p2  : \u1.add_ln700_5_reg_422 ;
  assign _007_ = \u1.ap_CS_fsm  ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.5-127.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:122.9-122.79" *) \u1.add_ln700_2_fu_245_p2  : \u1.add_ln700_2_reg_416 ;
  assign _010_ = \u1.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:112.5-118.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:112.9-112.23" *) 1'h0 : 1'h1;
  assign _009_ = \u1.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:104.5-108.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:104.9-104.23" *) 1'h1 : \u1.ap_NS_fsm ;
  assign \u1.sub_ln214_1_fu_263_p2  = { \u1.nonce_input_V [0], 3'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:243.33-243.78" *) { \u1.nonce_input_V [2:0], 1'h0 };
  assign \u1.sub_ln214_2_fu_364_p2  = $signed({ \u1.tmp_reg_435 , 3'h0 }) - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:245.33-245.97" *) $signed(\u1.trunc_ln1503_6_reg_428 );
  assign \u1.sub_ln214_fu_191_p2  = { \u1.nonce_input_V [2:1], 2'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:18.17-21.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_1_2_1.v:247.31-247.74" *) \u1.nonce_input_V [4:1];
  assign \u2.add_ln214_1_fu_201_p2  = $signed(4'h7) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:159.33-159.77" *) $signed(\u2.add_ln214_fu_145_p2 );
  assign \u2.add_ln214_2_fu_207_p2  = $signed(2'h2) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:161.33-161.78" *) $signed(\u2.sub_ln214_fu_183_p2 );
  assign \u2.add_ln214_3_fu_306_p2  = $signed(4'h7) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:163.33-163.79" *) $signed(\u2.sub_ln214_1_fu_283_p2 );
  assign \u2.add_ln214_4_fu_312_p2  = $signed(2'h2) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:165.33-165.73" *) $signed(\u2.and_ln_reg_433 );
  assign \u2.add_ln214_5_fu_372_p2  = $signed(1'h1) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:167.33-167.81" *) $signed(\u2.trunc_ln1503_6_reg_454 );
  assign \u2.add_ln214_6_fu_382_p2  = $signed(1'h1) + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:169.33-169.80" *) $signed(\u2.sub_ln214_2_fu_356_p2 );
  assign \u2.add_ln214_fu_145_p2  = { \u2.nonce_input_V [1:0], 2'h0 } + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:171.31-171.74" *) \u2.nonce_input_V [3:0];
  assign \u2.add_ln700_1_fu_231_p2  = \u2.mul_ln700_3_fu_219_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:173.33-173.78" *) \u2.mul_ln700_2_fu_213_p2 ;
  assign \u2.add_ln700_2_fu_237_p2  = \u2.add_ln700_1_fu_231_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:175.33-175.76" *) \u2.add_ln700_fu_225_p2 ;
  assign \u2.add_ln700_3_fu_327_p2  = \u2.mul_ln700_4_fu_289_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:177.33-177.74" *) { \u2.mul_ln700_5_fu_294_p2 , 2'h0 };
  assign \u2.add_ln700_4_fu_333_p2  = \u2.mul_ln700_7_fu_322_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:179.33-179.78" *) \u2.mul_ln700_6_fu_317_p2 ;
  assign \u2.add_ln700_5_fu_339_p2  = \u2.add_ln700_4_fu_333_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:181.33-181.78" *) \u2.add_ln700_3_fu_327_p2 ;
  assign \u2.add_ln700_6_fu_366_p2  = \u2.mul_ln700_9_fu_361_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:183.33-183.78" *) \u2.mul_ln700_8_fu_345_p2 ;
  assign \u2.add_ln700_7_fu_393_p2  = \u2.mul_ln700_11_fu_388_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:185.33-185.80" *) \u2.mul_ln700_10_fu_377_p2 ;
  assign \u2.add_ln700_fu_225_p2  = \u2.mul_ln700_fu_189_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:187.31-187.74" *) \u2.mul_ln700_1_fu_195_p2 ;
  assign \u2.mul_ln700_10_fu_377_p2  = $signed(\u2.add_ln214_5_fu_372_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:199.34-199.95" *) $signed(\u2.add_ln700_2_reg_438 );
  assign \u2.mul_ln700_11_fu_388_p2  = $signed(\u2.add_ln214_6_fu_382_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:201.34-201.95" *) $signed(\u2.add_ln700_5_reg_466 );
  assign \u2.mul_ln700_1_fu_195_p2  = $signed(\u2.sub_ln214_fu_183_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:203.33-203.94" *) $signed(\u2.in_port_V [3:0]);
  assign \u2.mul_ln700_2_fu_213_p2  = $signed(\u2.add_ln214_1_fu_201_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:205.33-205.99" *) $signed(\u2.in_port_V [15:12]);
  assign \u2.mul_ln700_3_fu_219_p2  = $signed(\u2.add_ln214_2_fu_207_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:207.33-207.98" *) $signed(\u2.in_port_V [7:4]);
  assign \u2.mul_ln700_4_fu_289_p2  = $signed(\u2.sub_ln214_1_fu_283_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:209.33-209.97" *) $signed(\u2.trunc_ln1503_2_reg_413 );
  assign \u2.mul_ln700_5_fu_294_p2  = $signed(\u2.trunc_ln700_reg_449 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:211.33-211.86" *) $signed(\u2.tmp_2_reg_428 );
  assign \u2.mul_ln700_6_fu_317_p2  = $signed(\u2.add_ln214_3_fu_306_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:213.33-213.97" *) $signed(\u2.trunc_ln1503_3_reg_418 );
  assign \u2.mul_ln700_7_fu_322_p2  = $signed(\u2.add_ln214_4_fu_312_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:215.33-215.97" *) $signed(\u2.trunc_ln1503_1_reg_408 );
  assign \u2.mul_ln700_8_fu_345_p2  = $signed(\u2.trunc_ln1503_6_reg_454 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:217.33-217.95" *) $signed(\u2.add_ln700_2_reg_438 );
  assign \u2.mul_ln700_9_fu_361_p2  = $signed(\u2.sub_ln214_2_fu_356_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:219.33-219.94" *) $signed(\u2.add_ln700_5_reg_466 );
  assign \u2.mul_ln700_fu_189_p2  = $signed(\u2.add_ln214_fu_145_p2 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:221.31-221.95" *) $signed(\u2.in_port_V [11:8]);
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:261.1-263.4" *)
  always @(posedge \u2.ap_clk )
    \u2.and_ln_reg_433 [1:0] <= 2'h0;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:128.1-132.4" *)
  always @(posedge \u2.ap_clk )
    \u2.add_ln700_5_reg_466  <= _015_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.trunc_ln1503_1_reg_408  <= _020_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.trunc_ln1503_2_reg_413  <= _021_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.trunc_ln1503_3_reg_418  <= _022_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.trunc_ln214_1_reg_423  <= _024_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.tmp_2_reg_428  <= _018_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.and_ln_reg_433 [3:2] <= _016_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.add_ln700_2_reg_438  <= _014_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.trunc_ln214_2_reg_444  <= _025_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.trunc_ln700_reg_449  <= _026_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.trunc_ln1503_6_reg_454  <= _023_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:112.1-126.4" *)
  always @(posedge \u2.ap_clk )
    \u2.tmp_reg_461  <= _019_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:104.1-110.4" *)
  always @(posedge \u2.ap_clk )
    \u2.ap_CS_fsm  <= _017_;
  function [2:0] _129_;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:143.5-156.12|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _129_ = b[2:0];
      3'b?1?:
        _129_ = b[5:3];
      3'b1??:
        _129_ = b[8:6];
      default:
        _129_ = a;
    endcase
  endfunction
  assign \u2.ap_NS_fsm  = _129_(3'hx, 9'h0a1, { _029_, _028_, _027_ });
  assign _027_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:143.5-156.12|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:0.0-0.0" *) 3'h4;
  assign _028_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:143.5-156.12|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:0.0-0.0" *) 2'h2;
  assign _029_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:143.5-156.12|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:0.0-0.0" *) 1'h1;
  assign \u2.out_port_V_ap_vld  = \u2.ap_CS_fsm [2] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:135.5-139.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:135.9-135.35" *) 1'h1 : 1'h0;
  assign _015_ = \u2.ap_CS_fsm [1] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:129.5-131.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:129.9-129.35" *) \u2.add_ln700_5_fu_339_p2  : \u2.add_ln700_5_reg_466 ;
  assign _019_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.nonce_input_V [2] : \u2.tmp_reg_461 ;
  assign _023_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.nonce_input_V [5:2] : \u2.trunc_ln1503_6_reg_454 ;
  assign _026_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.in_port_V [1:0] : \u2.trunc_ln700_reg_449 ;
  assign _025_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.nonce_input_V [0] : \u2.trunc_ln214_2_reg_444 ;
  assign _014_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.add_ln700_2_fu_237_p2  : \u2.add_ln700_2_reg_438 ;
  assign _016_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.nonce_input_V [2:1] : \u2.and_ln_reg_433 [3:2];
  assign _018_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.nonce_input_V [2:1] : \u2.tmp_2_reg_428 ;
  assign _024_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.nonce_input_V [2:0] : \u2.trunc_ln214_1_reg_423 ;
  assign _022_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.in_port_V [15:12] : \u2.trunc_ln1503_3_reg_418 ;
  assign _021_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.in_port_V [11:8] : \u2.trunc_ln1503_2_reg_413 ;
  assign _020_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.5-125.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:113.9-113.35" *) \u2.in_port_V [7:4] : \u2.trunc_ln1503_1_reg_408 ;
  assign _017_ = \u2.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:105.5-109.8|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:105.9-105.23" *) 3'h1 : \u2.ap_NS_fsm ;
  assign \u2.sub_ln214_1_fu_283_p2  = { \u2.trunc_ln214_2_reg_444 , 3'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:233.33-233.78" *) { \u2.trunc_ln214_1_reg_423 , 1'h0 };
  assign \u2.sub_ln214_2_fu_356_p2  = $signed({ \u2.tmp_reg_461 , 3'h0 }) - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:235.33-235.97" *) $signed(\u2.trunc_ln1503_6_reg_454 );
  assign \u2.sub_ln214_fu_183_p2  = { \u2.nonce_input_V [2:1], 2'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:23.16-26.50|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/kalman_3_4_4.v:237.31-237.74" *) \u2.nonce_input_V [4:1];
  assign _030_ = v1 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.12-33.25" *) _033_;
  assign _031_ = v2 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.12-37.25" *) _034_;
  assign _032_ = v1_buf && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.24-44.40" *) v2_buf;
  assign _033_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.18-33.25" *) v1_buf;
  assign _034_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.18-37.25" *) v2_buf;
  assign _035_ = _036_ || (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.22-44.73" *) _006_;
  assign _036_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:44.22-44.41" *) _032_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    v1_buf <= _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    output1_buf <= _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    v2_buf <= _003_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:28.4-42.7" *)
  always @(posedge ap_clk)
    output2_buf <= _001_;
  assign _037_ = _031_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.12-37.25|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.8-40.11" *) output2 : output2_buf;
  assign _001_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.6-41.9" *) output2_buf : _037_;
  assign _038_ = _031_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.12-37.25|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:37.8-40.11" *) 1'h1 : v2_buf;
  assign _003_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.6-41.9" *) 1'h0 : _038_;
  assign _039_ = _030_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.12-33.25|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.8-36.11" *) output1 : output1_buf;
  assign _000_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.6-41.9" *) output1_buf : _039_;
  assign _040_ = _030_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.12-33.25|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:33.8-36.11" *) 1'h1 : v1_buf;
  assign _002_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.9-29.15|/data/zhiyuany/property_mining/seq_dreamminer/kalman_wrapper_1_4/top.v:29.6-41.9" *) 1'h0 : _040_;
  assign \u2.and_ln214_1_fu_349_p3  = { \u2.tmp_reg_461 , 3'h0 };
  assign \u2.and_ln_fu_175_p3  = { \u2.nonce_input_V [2:1], 2'h0 };
  assign \u2.ap_CS_fsm_state1  = \u2.ap_CS_fsm [0];
  assign \u2.ap_CS_fsm_state2  = \u2.ap_CS_fsm [1];
  assign \u2.ap_CS_fsm_state3  = \u2.ap_CS_fsm [2];
  assign \u2.out_port_V  = { \u2.add_ln700_7_fu_393_p2 , \u2.add_ln700_6_fu_366_p2  };
  assign \u2.shl_ln1_fu_298_p3  = { \u2.mul_ln700_5_fu_294_p2 , 2'h0 };
  assign \u2.shl_ln214_1_fu_269_p3  = { \u2.trunc_ln214_1_reg_423 , 1'h0 };
  assign \u2.shl_ln214_2_fu_276_p3  = { \u2.trunc_ln214_2_reg_444 , 3'h0 };
  assign \u2.shl_ln_fu_137_p3  = { \u2.nonce_input_V [1:0], 2'h0 };
  assign \u2.tmp_2_fu_165_p4  = \u2.nonce_input_V [2:1];
  assign \u2.trunc_ln1503_1_fu_99_p4  = \u2.in_port_V [7:4];
  assign \u2.trunc_ln1503_2_fu_109_p4  = \u2.in_port_V [11:8];
  assign \u2.trunc_ln1503_3_fu_119_p4  = \u2.in_port_V [15:12];
  assign \u2.trunc_ln1503_4_fu_129_p1  = \u2.nonce_input_V [3:0];
  assign \u2.trunc_ln1503_5_fu_151_p4  = \u2.nonce_input_V [4:1];
  assign \u2.trunc_ln1503_fu_95_p1  = \u2.in_port_V [3:0];
  assign \u2.trunc_ln214_1_fu_161_p1  = \u2.nonce_input_V [2:0];
  assign \u2.trunc_ln214_2_fu_243_p1  = \u2.nonce_input_V [0];
  assign \u2.trunc_ln214_fu_133_p1  = \u2.nonce_input_V [1:0];
  assign \u2.trunc_ln700_fu_247_p1  = \u2.in_port_V [1:0];
  assign \u2.ap_clk  = ap_clk;
  assign \u2.ap_rst  = ap_rst;
  assign \u2.in_port_V  = in_port_V;
  assign \u2.nonce_input_V  = nonce_input_V;
  assign { _004_, output2 } = \u2.out_port_V ;
  assign v2 = \u2.out_port_V_ap_vld ;
  assign \u1.and_ln214_1_fu_357_p3  = { \u1.tmp_reg_435 , 3'h0 };
  assign \u1.and_ln_fu_183_p3  = { \u1.nonce_input_V [2:1], 2'h0 };
  assign \u1.ap_CS_fsm_pp0_stage0  = \u1.ap_CS_fsm ;
  assign \u1.ap_block_pp0_stage0  = 1'h0;
  assign \u1.ap_block_pp0_stage0_01001  = 1'h0;
  assign \u1.ap_block_pp0_stage0_11001  = 1'h0;
  assign \u1.ap_block_pp0_stage0_subdone  = 1'h0;
  assign \u1.ap_block_state1_pp0_stage0_iter0  = 1'h0;
  assign \u1.ap_block_state2_pp0_stage0_iter1  = 1'h0;
  assign \u1.ap_enable_pp0  = 1'h1;
  assign \u1.ap_idle_pp0  = 1'h0;
  assign \u1.ap_reset_idle_pp0  = 1'h0;
  assign \u1.out_port_V  = { \u1.add_ln700_7_fu_401_p2 , \u1.add_ln700_6_fu_374_p2  };
  assign \u1.shl_ln1_fu_285_p3  = { \u1.mul_ln700_5_fu_279_p2 , 2'h0 };
  assign \u1.shl_ln214_1_fu_165_p3  = { \u1.nonce_input_V [2:0], 1'h0 };
  assign \u1.shl_ln214_2_fu_255_p3  = { \u1.nonce_input_V [0], 3'h0 };
  assign \u1.shl_ln_fu_137_p3  = { \u1.nonce_input_V [1:0], 2'h0 };
  assign \u1.tmp_2_fu_173_p4  = \u1.nonce_input_V [2:1];
  assign \u1.trunc_ln1503_1_fu_99_p4  = \u1.in_port_V [7:4];
  assign \u1.trunc_ln1503_2_fu_109_p4  = \u1.in_port_V [11:8];
  assign \u1.trunc_ln1503_3_fu_119_p4  = \u1.in_port_V [15:12];
  assign \u1.trunc_ln1503_4_fu_129_p1  = \u1.nonce_input_V [3:0];
  assign \u1.trunc_ln1503_5_fu_151_p4  = \u1.nonce_input_V [4:1];
  assign \u1.trunc_ln1503_fu_95_p1  = \u1.in_port_V [3:0];
  assign \u1.trunc_ln214_1_fu_161_p1  = \u1.nonce_input_V [2:0];
  assign \u1.trunc_ln214_2_fu_251_p1  = \u1.nonce_input_V [0];
  assign \u1.trunc_ln214_fu_133_p1  = \u1.nonce_input_V [1:0];
  assign \u1.trunc_ln700_fu_275_p1  = \u1.in_port_V [1:0];
  assign \u1.ap_clk  = ap_clk;
  assign \u1.ap_rst  = ap_rst;
  assign \u1.in_port_V  = in_port_V;
  assign \u1.nonce_input_V  = nonce_input_V;
  assign { _005_, output1 } = \u1.out_port_V ;
  assign v1 = \u1.out_port_V_ap_vld ;
endmodule
