/* Generated by Yosys 0.29+34 (git sha1 57c9eb70f, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:1.1-91.10" *)
module top(ap_clk, ap_rst, vars_V, out_V, out_V_ap_vld);
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire [3:0] _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire [3:0] _001_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire [3:0] _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire [3:0] _003_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire [3:0] _004_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire [3:0] _005_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire _006_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire _008_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire _009_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire _010_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  wire _011_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.51-89.80" *)
  wire _012_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.113-89.142" *)
  wire _013_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.175-89.204" *)
  wire _014_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:66.1-72.4" *)
  wire [1:0] _015_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:74.1-80.4" *)
  wire [3:0] _016_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:82.1-88.4" *)
  wire [3:0] _017_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:90.1-96.4" *)
  wire [3:0] _018_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:122.1-138.4" *)
  wire [1:0] _019_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:107.10-107.69" *)
  wire _020_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:75.10-75.69" *)
  wire _021_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:154.33-154.57" *)
  wire _022_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:75.11-75.39" *)
  wire _023_;
  wire _024_;
  wire _025_;
  wire [3:0] _026_;
  wire [3:0] _027_;
  wire [3:0] _028_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:105.1-111.4" *)
  wire [3:0] _029_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:73.1-79.4" *)
  wire [4:0] _030_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:81.1-87.4" *)
  wire [3:0] _031_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:89.1-95.4" *)
  wire [3:0] _032_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:97.1-103.4" *)
  wire [3:0] _033_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:105.1-111.4" *)
  wire [3:0] _034_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:105.1-111.4" *)
  wire [3:0] _035_;
  wire [2:0] _036_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.10-106.69" *)
  wire _037_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:114.10-114.69" *)
  wire _038_;
  wire _039_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.11-106.39" *)
  wire _040_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:180.33-180.57" *)
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire [3:0] _047_;
  wire [3:0] _048_;
  wire [3:0] _049_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.12-62.29" *)
  wire _050_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.12-66.29" *)
  wire _051_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.12-70.29" *)
  wire _052_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.12-74.29" *)
  wire _053_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.12-78.29" *)
  wire _054_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.12-82.29" *)
  wire _055_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.25-89.45" *)
  wire _056_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.87-89.107" *)
  wire _057_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.22-89.144" *)
  wire _058_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.149-89.169" *)
  wire _059_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.22-89.206" *)
  wire _060_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.20-62.29" *)
  wire _061_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.20-66.29" *)
  wire _062_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.20-70.29" *)
  wire _063_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.20-74.29" *)
  wire _064_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.20-78.29" *)
  wire _065_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.20-82.29" *)
  wire _066_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.23-89.81" *)
  wire _067_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.85-89.143" *)
  wire _068_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.147-89.205" *)
  wire _069_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.23-89.46" *)
  wire _070_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.85-89.108" *)
  wire _071_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.147-89.170" *)
  wire _072_;
  wire [3:0] _073_;
  wire [3:0] _074_;
  wire [3:0] _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire [3:0] _079_;
  wire [3:0] _080_;
  wire [3:0] _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:1.18-1.24" *)
  input ap_clk;
  wire ap_clk;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:1.32-1.38" *)
  input ap_rst;
  wire ap_rst;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:4.22-4.27" *)
  output [3:0] out_V;
  wire [3:0] out_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:5.16-5.28" *)
  output out_V_ap_vld;
  wire out_V_ap_vld;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:15.15-15.24" *)
  wire [3:0] outputu_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:18.14-18.27" *)
  reg [3:0] outputu_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:28.15-28.24" *)
  wire [3:0] outputu_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:31.14-31.27" *)
  reg [3:0] outputu_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:13.15-13.24" *)
  wire [3:0] outputx_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:16.14-16.27" *)
  reg [3:0] outputx_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:26.15-26.24" *)
  wire [3:0] outputx_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:29.14-29.27" *)
  reg [3:0] outputx_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:14.15-14.24" *)
  wire [3:0] outputy_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:17.14-17.27" *)
  reg [3:0] outputy_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:27.15-27.24" *)
  wire [3:0] outputy_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:30.14-30.27" *)
  reg [3:0] outputy_2_buf;
  (* hdlname = "u1 Uoutport_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:34.15-34.25" *)
  wire [3:0] \u1.Uoutport_V ;
  (* hdlname = "u1 Uoutport_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:35.10-35.27" *)
  wire \u1.Uoutport_V_ap_vld ;
  (* hdlname = "u1 Xoutport_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:30.15-30.25" *)
  wire [3:0] \u1.Xoutport_V ;
  (* hdlname = "u1 Xoutport_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:31.10-31.27" *)
  wire \u1.Xoutport_V_ap_vld ;
  (* hdlname = "u1 Youtport_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:32.15-32.25" *)
  wire [3:0] \u1.Youtport_V ;
  (* hdlname = "u1 Youtport_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:33.10-33.27" *)
  wire \u1.Youtport_V_ap_vld ;
  (* hdlname = "u1 add_ln214_1_fu_167_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:57.14-57.35" *)
  wire [3:0] \u1.add_ln214_1_fu_167_p2 ;
  (* hdlname = "u1 add_ln214_fu_185_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:48.14-48.33" *)
  wire [3:0] \u1.add_ln214_fu_185_p2 ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u1 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:42.41-42.50" *)
  reg [1:0] \u1.ap_CS_fsm  = 2'h1;
  (* hdlname = "u1 ap_CS_fsm_state1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:43.9-43.25" *)
  wire \u1.ap_CS_fsm_state1 ;
  (* hdlname = "u1 ap_CS_fsm_state2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:45.9-45.25" *)
  wire \u1.ap_CS_fsm_state2 ;
  (* hdlname = "u1 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:59.13-59.22" *)
  wire [1:0] \u1.ap_NS_fsm ;
  (* hdlname = "u1 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:27.9-27.15" *)
  wire \u1.ap_clk ;
  (* hdlname = "u1 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:28.9-28.15" *)
  wire \u1.ap_rst ;
  (* hdlname = "u1 icmp_ln887_fu_125_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:46.14-46.34" *)
  wire \u1.icmp_ln887_fu_125_p2 ;
  (* hdlname = "u1 p_0423_0_reg_81" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:50.13-50.28" *)
  reg [3:0] \u1.p_0423_0_reg_81 ;
  (* hdlname = "u1 p_0426_0_reg_72" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:49.13-49.28" *)
  reg [3:0] \u1.p_0426_0_reg_72 ;
  (* hdlname = "u1 shl_ln214_1_fu_155_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:55.14-55.35" *)
  wire [3:0] \u1.shl_ln214_1_fu_155_p2 ;
  (* hdlname = "u1 shl_ln214_fu_131_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:52.14-52.33" *)
  wire [3:0] \u1.shl_ln214_fu_131_p2 ;
  (* hdlname = "u1 sub_ln214_3_fu_161_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:56.14-56.35" *)
  wire [3:0] \u1.sub_ln214_3_fu_161_p2 ;
  (* hdlname = "u1 t1_V_reg_91" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:51.19-51.30" *)
  reg [3:0] \u1.t1_V_reg_91 ;
  (* hdlname = "u1 t2_V_fu_137_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:53.20-53.34" *)
  wire [3:0] \u1.t2_V_fu_137_p2 ;
  (* hdlname = "u1 t4_V_fu_143_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:54.14-54.28" *)
  wire [3:0] \u1.t4_V_fu_143_p2 ;
  (* hdlname = "u1 t6_V_fu_149_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:58.14-58.28" *)
  wire [3:0] \u1.t6_V_fu_149_p2 ;
  (* hdlname = "u1 u_var_V_2_fu_173_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:44.14-44.33" *)
  wire [3:0] \u1.u_var_V_2_fu_173_p2 ;
  (* hdlname = "u1 vars_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:29.15-29.21" *)
  wire [11:0] \u1.vars_V ;
  (* hdlname = "u1 x_var_V_fu_101_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:41.14-41.31" *)
  wire [3:0] \u1.x_var_V_fu_101_p1 ;
  (* hdlname = "u1 y_var_V_1_fu_179_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:47.14-47.33" *)
  wire [3:0] \u1.y_var_V_1_fu_179_p2 ;
  (* hdlname = "u2 Uoutport_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:37.15-37.25" *)
  wire [3:0] \u2.Uoutport_V ;
  (* hdlname = "u2 Uoutport_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:38.10-38.27" *)
  wire \u2.Uoutport_V_ap_vld ;
  (* hdlname = "u2 Xoutport_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:33.15-33.25" *)
  wire [3:0] \u2.Xoutport_V ;
  (* hdlname = "u2 Xoutport_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:34.10-34.27" *)
  wire \u2.Xoutport_V_ap_vld ;
  (* hdlname = "u2 Youtport_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:35.15-35.25" *)
  wire [3:0] \u2.Youtport_V ;
  (* hdlname = "u2 Youtport_V_ap_vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:36.10-36.27" *)
  wire \u2.Youtport_V_ap_vld ;
  (* hdlname = "u2 add_ln214_1_fu_177_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:64.14-64.35" *)
  wire [3:0] \u2.add_ln214_1_fu_177_p2 ;
  (* hdlname = "u2 add_ln214_fu_195_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:53.14-53.33" *)
  wire [3:0] \u2.add_ln214_fu_195_p2 ;
  (* hdlname = "u2 add_ln214_reg_229" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:54.13-54.30" *)
  reg [3:0] \u2.add_ln214_reg_229 ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u2 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:45.41-45.50" *)
  reg [4:0] \u2.ap_CS_fsm  = 5'h01;
  (* hdlname = "u2 ap_CS_fsm_state1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:46.9-46.25" *)
  wire \u2.ap_CS_fsm_state1 ;
  (* hdlname = "u2 ap_CS_fsm_state2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:49.9-49.25" *)
  wire \u2.ap_CS_fsm_state2 ;
  (* hdlname = "u2 ap_CS_fsm_state5" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:56.9-56.25" *)
  wire \u2.ap_CS_fsm_state5 ;
  (* hdlname = "u2 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:66.13-66.22" *)
  wire [4:0] \u2.ap_NS_fsm ;
  (* hdlname = "u2 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:30.9-30.15" *)
  wire \u2.ap_clk ;
  (* hdlname = "u2 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:31.9-31.15" *)
  wire \u2.ap_rst ;
  (* hdlname = "u2 icmp_ln887_fu_135_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:50.14-50.34" *)
  wire \u2.icmp_ln887_fu_135_p2 ;
  (* hdlname = "u2 p_0423_0_reg_91" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:57.13-57.28" *)
  reg [3:0] \u2.p_0423_0_reg_91 ;
  (* hdlname = "u2 p_0426_0_reg_82" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:55.13-55.28" *)
  reg [3:0] \u2.p_0426_0_reg_82 ;
  (* hdlname = "u2 shl_ln214_1_fu_165_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:62.14-62.35" *)
  wire [3:0] \u2.shl_ln214_1_fu_165_p2 ;
  (* hdlname = "u2 shl_ln214_fu_141_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:59.14-59.33" *)
  wire [3:0] \u2.shl_ln214_fu_141_p2 ;
  (* hdlname = "u2 sub_ln214_3_fu_171_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:63.14-63.35" *)
  wire [3:0] \u2.sub_ln214_3_fu_171_p2 ;
  (* hdlname = "u2 t1_V_reg_101" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:58.19-58.31" *)
  reg [3:0] \u2.t1_V_reg_101 ;
  (* hdlname = "u2 t2_V_fu_147_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:60.20-60.34" *)
  wire [3:0] \u2.t2_V_fu_147_p2 ;
  (* hdlname = "u2 t4_V_fu_153_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:61.14-61.28" *)
  wire [3:0] \u2.t4_V_fu_153_p2 ;
  (* hdlname = "u2 t6_V_fu_159_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:65.14-65.28" *)
  wire [3:0] \u2.t6_V_fu_159_p2 ;
  (* hdlname = "u2 u_var_V_2_fu_183_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:47.14-47.33" *)
  wire [3:0] \u2.u_var_V_2_fu_183_p2 ;
  (* hdlname = "u2 u_var_V_2_reg_219" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:48.13-48.30" *)
  reg [3:0] \u2.u_var_V_2_reg_219 ;
  (* hdlname = "u2 vars_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:32.15-32.21" *)
  wire [11:0] \u2.vars_V ;
  (* hdlname = "u2 x_var_V_fu_111_p1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:44.14-44.31" *)
  wire [3:0] \u2.x_var_V_fu_111_p1 ;
  (* hdlname = "u2 y_var_V_1_fu_189_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:51.14-51.33" *)
  wire [3:0] \u2.y_var_V_1_fu_189_p2 ;
  (* hdlname = "u2 y_var_V_1_reg_224" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:52.13-52.30" *)
  reg [3:0] \u2.y_var_V_1_reg_224 ;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:2.22-2.28" *)
  input [11:0] vars_V;
  wire [11:0] vars_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:12.9-12.13" *)
  wire vu_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:7.8-7.16" *)
  reg vu_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:25.9-25.13" *)
  wire vu_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:20.8-20.16" *)
  reg vu_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:10.9-10.13" *)
  wire vx_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:8.8-8.16" *)
  reg vx_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:23.9-23.13" *)
  wire vx_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:21.8-21.16" *)
  reg vx_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:11.9-11.13" *)
  wire vy_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:9.8-9.16" *)
  reg vy_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:24.9-24.13" *)
  wire vy_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:22.8-22.16" *)
  reg vy_2_buf;
  always @* if (1'h1) assert(_060_);
  assign _012_ = outputu_1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.51-89.80" *) outputu_2_buf;
  assign _013_ = outputx_1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.113-89.142" *) outputx_2_buf;
  assign _014_ = outputy_1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.175-89.204" *) outputy_2_buf;
  assign \u1.add_ln214_1_fu_167_p2  = \u1.p_0423_0_reg_81  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:146.33-146.72" *) \u1.sub_ln214_3_fu_161_p2 ;
  assign \u1.add_ln214_fu_185_p2  = \u1.p_0426_0_reg_72  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:148.31-148.53" *) 1'h1;
  assign \u1.u_var_V_2_fu_173_p2  = \u1.add_ln214_1_fu_167_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:168.31-168.69" *) \u1.t6_V_fu_149_p2 ;
  assign \u1.y_var_V_1_fu_179_p2  = \u1.p_0423_0_reg_81  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:172.31-172.68" *) \u1.u_var_V_2_fu_173_p2 ;
  assign _020_ = \u1.icmp_ln887_fu_125_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:107.10-107.69" *) \u1.ap_CS_fsm [1];
  assign _021_ = _023_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:75.10-75.69" *) \u1.ap_CS_fsm [1];
  assign _022_ = \u1.p_0426_0_reg_72  == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:154.33-154.57" *) 4'hf;
  assign _023_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:75.11-75.39" *) \u1.icmp_ln887_fu_125_p2 ;
  assign \u1.t4_V_fu_143_p2  = $signed(\u1.t1_V_reg_91 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:164.26-164.72" *) $signed(\u1.t2_V_fu_137_p2 );
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:90.1-96.4" *)
  always @(posedge \u1.ap_clk )
    \u1.t1_V_reg_91  <= _018_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:82.1-88.4" *)
  always @(posedge \u1.ap_clk )
    \u1.p_0426_0_reg_72  <= _017_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:74.1-80.4" *)
  always @(posedge \u1.ap_clk )
    \u1.p_0423_0_reg_81  <= _016_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:66.1-72.4" *)
  always @(posedge \u1.ap_clk )
    \u1.ap_CS_fsm  <= _015_;
  assign _019_ = _020_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:128.13-132.16|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:128.17-128.78" *) 2'h1 : 2'h2;
  assign _024_ = \u1.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:123.5-137.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:0.0-0.0" *) 2'h2;
  function [1:0] _104_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:123.5-137.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _104_ = b[1:0];
      2'b1?:
        _104_ = b[3:2];
      default:
        _104_ = a;
    endcase
  endfunction
  assign \u1.ap_NS_fsm  = _104_(2'hx, { 2'h2, _019_ }, { _025_, _024_ });
  assign _025_ = \u1.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:123.5-137.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:0.0-0.0" *) 1'h1;
  assign \u1.Youtport_V_ap_vld  = _020_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:115.5-119.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:115.9-115.70" *) 1'h1 : 1'h0;
  assign _026_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:93.14-95.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:93.18-93.44" *) \u1.vars_V [11:8] : \u1.t1_V_reg_91 ;
  assign _018_ = _021_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:91.5-95.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:91.9-91.70" *) \u1.u_var_V_2_fu_173_p2  : _026_;
  assign _027_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:85.14-87.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:85.18-85.44" *) \u1.vars_V [3:0] : \u1.p_0426_0_reg_72 ;
  assign _017_ = _021_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:83.5-87.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:83.9-83.70" *) \u1.add_ln214_fu_185_p2  : _027_;
  assign _028_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:77.14-79.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:77.18-77.44" *) \u1.vars_V [7:4] : \u1.p_0423_0_reg_81 ;
  assign _016_ = _021_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:75.5-79.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:75.9-75.70" *) \u1.y_var_V_1_fu_179_p2  : _028_;
  assign _015_ = \u1.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:67.5-71.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:67.9-67.23" *) 2'h1 : \u1.ap_NS_fsm ;
  assign \u1.sub_ln214_3_fu_161_p2  = 1'h0 - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:160.33-160.61" *) { \u1.p_0423_0_reg_81 [1:0], 2'h0 };
  assign \u1.t2_V_fu_137_p2  = { \u1.p_0426_0_reg_72 [1:0], 2'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:162.26-162.63" *) \u1.p_0426_0_reg_72 ;
  assign \u1.t6_V_fu_149_p2  = $signed(\u1.t1_V_reg_91 ) - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:166.26-166.72" *) $signed(\u1.t4_V_fu_143_p2 );
  assign \u1.icmp_ln887_fu_125_p2  = _022_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:33.17-41.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq1.v:154.32-154.72" *) 1'h1 : 1'h0;
  assign \u2.add_ln214_1_fu_177_p2  = \u2.p_0423_0_reg_91  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:170.33-170.72" *) \u2.sub_ln214_3_fu_171_p2 ;
  assign \u2.add_ln214_fu_195_p2  = \u2.p_0426_0_reg_82  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:172.31-172.53" *) 1'h1;
  assign \u2.u_var_V_2_fu_183_p2  = \u2.add_ln214_1_fu_177_p2  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:194.31-194.69" *) \u2.t6_V_fu_159_p2 ;
  assign \u2.y_var_V_1_fu_189_p2  = \u2.p_0423_0_reg_91  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:198.31-198.68" *) \u2.u_var_V_2_fu_183_p2 ;
  assign _037_ = _040_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.10-106.69" *) \u2.ap_CS_fsm [1];
  assign _038_ = \u2.icmp_ln887_fu_135_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:114.10-114.69" *) \u2.ap_CS_fsm [1];
  assign _039_ = | { _046_, _043_ };
  assign _040_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.11-106.39" *) \u2.icmp_ln887_fu_135_p2 ;
  assign _041_ = \u2.p_0426_0_reg_82  == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:180.33-180.57" *) 4'hf;
  assign \u2.t4_V_fu_153_p2  = $signed(\u2.t1_V_reg_101 ) * (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:190.26-190.73" *) $signed(\u2.t2_V_fu_147_p2 );
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:105.1-111.4" *)
  always @(posedge \u2.ap_clk )
    \u2.u_var_V_2_reg_219  <= _034_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:105.1-111.4" *)
  always @(posedge \u2.ap_clk )
    \u2.y_var_V_1_reg_224  <= _035_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:105.1-111.4" *)
  always @(posedge \u2.ap_clk )
    \u2.add_ln214_reg_229  <= _029_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:97.1-103.4" *)
  always @(posedge \u2.ap_clk )
    \u2.t1_V_reg_101  <= _033_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:89.1-95.4" *)
  always @(posedge \u2.ap_clk )
    \u2.p_0426_0_reg_82  <= _032_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:81.1-87.4" *)
  always @(posedge \u2.ap_clk )
    \u2.p_0423_0_reg_91  <= _031_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:73.1-79.4" *)
  always @(posedge \u2.ap_clk )
    \u2.ap_CS_fsm  <= _030_;
  assign _036_ = _038_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:143.13-147.16|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:143.17-143.78" *) 3'h1 : 3'h4;
  assign _042_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:138.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:0.0-0.0" *) 2'h2;
  function [4:0] _137_;
    input [4:0] a;
    input [19:0] b;
    input [3:0] s;
    (* full_case = 32'd1 *)
    (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:138.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      4'b???1:
        _137_ = b[4:0];
      4'b??1?:
        _137_ = b[9:5];
      4'b?1??:
        _137_ = b[14:10];
      4'b1???:
        _137_ = b[19:15];
      default:
        _137_ = a;
    endcase
  endfunction
  assign \u2.ap_NS_fsm  = _137_(5'hxx, { 2'h0, _036_, 15'h2202 }, { _042_, _045_, _044_, _039_ });
  assign _043_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:138.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:0.0-0.0" *) 5'h10;
  assign _044_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:138.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:0.0-0.0" *) 4'h8;
  assign _045_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:138.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:0.0-0.0" *) 3'h4;
  assign _046_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:138.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:0.0-0.0" *) 1'h1;
  assign \u2.Youtport_V_ap_vld  = _038_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:130.5-134.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:130.9-130.70" *) 1'h1 : 1'h0;
  assign _029_ = _037_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.5-110.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.9-106.70" *) \u2.add_ln214_fu_195_p2  : \u2.add_ln214_reg_229 ;
  assign _035_ = _037_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.5-110.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.9-106.70" *) \u2.y_var_V_1_fu_189_p2  : \u2.y_var_V_1_reg_224 ;
  assign _034_ = _037_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.5-110.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:106.9-106.70" *) \u2.u_var_V_2_fu_183_p2  : \u2.u_var_V_2_reg_219 ;
  assign _047_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:100.14-102.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:100.18-100.44" *) \u2.vars_V [11:8] : \u2.t1_V_reg_101 ;
  assign _033_ = \u2.ap_CS_fsm [4] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:98.5-102.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:98.9-98.35" *) \u2.u_var_V_2_reg_219  : _047_;
  assign _048_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:92.14-94.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:92.18-92.44" *) \u2.vars_V [3:0] : \u2.p_0426_0_reg_82 ;
  assign _032_ = \u2.ap_CS_fsm [4] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:90.5-94.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:90.9-90.35" *) \u2.add_ln214_reg_229  : _048_;
  assign _049_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:84.14-86.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:84.18-84.44" *) \u2.vars_V [7:4] : \u2.p_0423_0_reg_91 ;
  assign _031_ = \u2.ap_CS_fsm [4] ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:82.5-86.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:82.9-82.35" *) \u2.y_var_V_1_reg_224  : _049_;
  assign _030_ = \u2.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:74.5-78.8|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:74.9-74.23" *) 5'h01 : \u2.ap_NS_fsm ;
  assign \u2.sub_ln214_3_fu_171_p2  = 1'h0 - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:186.33-186.61" *) { \u2.p_0423_0_reg_91 [1:0], 2'h0 };
  assign \u2.t2_V_fu_147_p2  = { \u2.p_0426_0_reg_82 [1:0], 2'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:188.26-188.63" *) \u2.p_0426_0_reg_82 ;
  assign \u2.t6_V_fu_159_p2  = $signed(\u2.t1_V_reg_101 ) - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:192.26-192.73" *) $signed(\u2.t4_V_fu_153_p2 );
  assign \u2.icmp_ln887_fu_135_p2  = _041_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:43.17-51.30|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/diffeq4.v:180.32-180.72" *) 1'h1 : 1'h0;
  assign _050_ = vu_1 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.12-62.29" *) _061_;
  assign _051_ = vu_2 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.12-66.29" *) _062_;
  assign _052_ = vx_1 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.12-70.29" *) _063_;
  assign _053_ = vx_2 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.12-74.29" *) _064_;
  assign _054_ = vy_1 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.12-78.29" *) _065_;
  assign _055_ = vy_2 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.12-82.29" *) _066_;
  assign _056_ = vu_1_buf && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.25-89.45" *) vu_2_buf;
  assign _057_ = vx_1_buf && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.87-89.107" *) vx_2_buf;
  assign _058_ = _067_ && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.22-89.144" *) _068_;
  assign _059_ = vy_1_buf && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.149-89.169" *) vy_2_buf;
  assign _060_ = _058_ && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.22-89.206" *) _069_;
  assign _061_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.20-62.29" *) vu_1_buf;
  assign _062_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.20-66.29" *) vu_2_buf;
  assign _063_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.20-70.29" *) vx_1_buf;
  assign _064_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.20-74.29" *) vx_2_buf;
  assign _065_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.20-78.29" *) vy_1_buf;
  assign _066_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.20-82.29" *) vy_2_buf;
  assign _067_ = _070_ || (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.23-89.81" *) _012_;
  assign _068_ = _071_ || (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.85-89.143" *) _013_;
  assign _069_ = _072_ || (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.147-89.205" *) _014_;
  assign _070_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.23-89.46" *) _056_;
  assign _071_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.85-89.108" *) _057_;
  assign _072_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:89.147-89.170" *) _059_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    vu_1_buf <= _006_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    vx_1_buf <= _008_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    vy_1_buf <= _010_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    outputx_1_buf <= _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    outputy_1_buf <= _004_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    outputu_1_buf <= _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    vu_2_buf <= _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    vx_2_buf <= _009_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    vy_2_buf <= _011_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    outputx_2_buf <= _003_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    outputy_2_buf <= _005_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:53.4-87.7" *)
  always @(posedge ap_clk)
    outputu_2_buf <= _001_;
  assign _073_ = _051_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.12-66.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.8-69.11" *) outputu_2 : outputu_2_buf;
  assign _001_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) outputu_2_buf : _073_;
  assign _074_ = _055_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.12-82.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.8-85.11" *) outputy_2 : outputy_2_buf;
  assign _005_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) outputy_2_buf : _074_;
  assign _075_ = _053_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.12-74.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.8-77.11" *) outputx_2 : outputx_2_buf;
  assign _003_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) outputx_2_buf : _075_;
  assign _076_ = _055_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.12-82.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:82.8-85.11" *) 1'h1 : vy_2_buf;
  assign _011_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) 1'h0 : _076_;
  assign _077_ = _053_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.12-74.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:74.8-77.11" *) 1'h1 : vx_2_buf;
  assign _009_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) 1'h0 : _077_;
  assign _078_ = _051_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.12-66.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:66.8-69.11" *) 1'h1 : vu_2_buf;
  assign _007_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) 1'h0 : _078_;
  assign _079_ = _050_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.12-62.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.8-65.11" *) outputu_1 : outputu_1_buf;
  assign _000_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) outputu_1_buf : _079_;
  assign _080_ = _054_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.12-78.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.8-81.11" *) outputy_1 : outputy_1_buf;
  assign _004_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) outputy_1_buf : _080_;
  assign _081_ = _052_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.12-70.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.8-73.11" *) outputx_1 : outputx_1_buf;
  assign _002_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) outputx_1_buf : _081_;
  assign _082_ = _054_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.12-78.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:78.8-81.11" *) 1'h1 : vy_1_buf;
  assign _010_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) 1'h0 : _082_;
  assign _083_ = _052_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.12-70.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:70.8-73.11" *) 1'h1 : vx_1_buf;
  assign _008_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) 1'h0 : _083_;
  assign _084_ = _050_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.12-62.29|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:62.8-65.11" *) 1'h1 : vu_1_buf;
  assign _006_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.9-54.15|/data/zhiyuany/property_mining/seq_dreamminer/diffeq_easy_wrapper_1_4/top.v:54.6-86.9" *) 1'h0 : _084_;
  assign \u2.Uoutport_V  = \u2.t1_V_reg_101 ;
  assign \u2.Uoutport_V_ap_vld  = \u2.Youtport_V_ap_vld ;
  assign \u2.Xoutport_V  = 4'hf;
  assign \u2.Xoutport_V_ap_vld  = \u2.Youtport_V_ap_vld ;
  assign \u2.Youtport_V  = \u2.p_0423_0_reg_91 ;
  assign \u2.ap_CS_fsm_state1  = \u2.ap_CS_fsm [0];
  assign \u2.ap_CS_fsm_state2  = \u2.ap_CS_fsm [1];
  assign \u2.ap_CS_fsm_state5  = \u2.ap_CS_fsm [4];
  assign \u2.shl_ln214_1_fu_165_p2  = { \u2.p_0423_0_reg_91 [1:0], 2'h0 };
  assign \u2.shl_ln214_fu_141_p2  = { \u2.p_0426_0_reg_82 [1:0], 2'h0 };
  assign \u2.x_var_V_fu_111_p1  = \u2.vars_V [3:0];
  assign outputu_2 = \u2.Uoutport_V ;
  assign vu_2 = \u2.Uoutport_V_ap_vld ;
  assign outputx_2 = \u2.Xoutport_V ;
  assign vx_2 = \u2.Xoutport_V_ap_vld ;
  assign outputy_2 = \u2.Youtport_V ;
  assign vy_2 = \u2.Youtport_V_ap_vld ;
  assign \u2.ap_clk  = ap_clk;
  assign \u2.ap_rst  = ap_rst;
  assign \u2.vars_V  = vars_V;
  assign \u1.Uoutport_V  = \u1.t1_V_reg_91 ;
  assign \u1.Uoutport_V_ap_vld  = \u1.Youtport_V_ap_vld ;
  assign \u1.Xoutport_V  = 4'hf;
  assign \u1.Xoutport_V_ap_vld  = \u1.Youtport_V_ap_vld ;
  assign \u1.Youtport_V  = \u1.p_0423_0_reg_81 ;
  assign \u1.ap_CS_fsm_state1  = \u1.ap_CS_fsm [0];
  assign \u1.ap_CS_fsm_state2  = \u1.ap_CS_fsm [1];
  assign \u1.shl_ln214_1_fu_155_p2  = { \u1.p_0423_0_reg_81 [1:0], 2'h0 };
  assign \u1.shl_ln214_fu_131_p2  = { \u1.p_0426_0_reg_72 [1:0], 2'h0 };
  assign \u1.x_var_V_fu_101_p1  = \u1.vars_V [3:0];
  assign outputu_1 = \u1.Uoutport_V ;
  assign vu_1 = \u1.Uoutport_V_ap_vld ;
  assign outputx_1 = \u1.Xoutport_V ;
  assign vx_1 = \u1.Xoutport_V_ap_vld ;
  assign outputy_1 = \u1.Youtport_V ;
  assign vy_1 = \u1.Youtport_V_ap_vld ;
  assign \u1.ap_clk  = ap_clk;
  assign \u1.ap_rst  = ap_rst;
  assign \u1.vars_V  = vars_V;
endmodule
