/* Generated by Yosys 0.29+34 (git sha1 57c9eb70f, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* keep =  1  *)
(* top =  1  *)
(* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:1.1-73.10" *)
module top(ap_clk, ap_rst, seed_V, num_V, out_V, out_V_ap_vld);
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire [2:0] _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire [2:0] _001_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire [3:0] _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire [3:0] _003_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire _004_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire _005_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire _006_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire _008_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  wire _009_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.47-71.68" *)
  wire _010_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.72-71.94" *)
  wire _011_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.98-71.124" *)
  wire _012_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.128-71.154" *)
  wire _013_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:72.1-78.4" *)
  wire [2:0] _014_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:64.1-70.4" *)
  wire [1:0] _015_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:80.1-86.4" *)
  wire _016_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:88.1-94.4" *)
  wire [3:0] _017_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:96.1-102.4" *)
  wire [5:0] _018_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:142.1-158.4" *)
  wire [1:0] _019_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:104.1-116.4" *)
  wire [3:0] _020_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:118.1-130.4" *)
  wire _021_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:132.1-140.4" *)
  wire _022_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:105.10-105.69" *)
  wire _023_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:133.10-133.71" *)
  wire _024_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:133.10-133.100" *)
  wire _025_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.49-135.110" *)
  wire _026_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.49-135.139" *)
  wire _027_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:148.18-148.77" *)
  wire _028_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:105.11-105.39" *)
  wire _029_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.50-135.76" *)
  wire _030_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:174.27-174.48" *)
  wire _031_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:176.33-176.58" *)
  wire _032_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.19-135.140" *)
  wire _033_;
  wire _034_;
  wire _035_;
  wire [5:0] _036_;
  wire [3:0] _037_;
  wire _038_;
  wire [2:0] _039_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:73.1-79.4" *)
  wire [2:0] _040_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:65.1-71.4" *)
  wire [2:0] _041_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:81.1-87.4" *)
  wire _042_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:89.1-95.4" *)
  wire [3:0] _043_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:97.1-103.4" *)
  wire [5:0] _044_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:143.1-162.4" *)
  wire [2:0] _045_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:105.1-117.4" *)
  wire [3:0] _046_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:119.1-131.4" *)
  wire _047_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:133.1-141.4" *)
  wire _048_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:106.10-106.69" *)
  wire _049_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:134.10-134.71" *)
  wire _050_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:134.10-134.100" *)
  wire _051_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.49-136.110" *)
  wire _052_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.49-136.139" *)
  wire _053_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:106.11-106.39" *)
  wire _054_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.50-136.76" *)
  wire _055_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:178.27-178.50" *)
  wire _056_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:180.33-180.58" *)
  wire _057_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.19-136.140" *)
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire [5:0] _062_;
  wire [3:0] _063_;
  wire _064_;
  wire [2:0] _065_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.12-54.26" *)
  wire _066_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.12-61.26" *)
  wire _067_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.24-71.40" *)
  wire _068_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.46-71.95" *)
  wire _069_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.46-71.125" *)
  wire _070_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.46-71.155" *)
  wire _071_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.19-54.26" *)
  wire _072_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.19-61.26" *)
  wire _073_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.22-71.156" *)
  wire _074_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.22-71.41" *)
  wire _075_;
  wire [2:0] _076_;
  wire [3:0] _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [2:0] _081_;
  wire [3:0] _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:12.15-12.23" *)
  wire [2:0] addr_V_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:16.14-16.26" *)
  reg [2:0] addr_V_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:23.15-23.23" *)
  wire [2:0] addr_V_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:27.14-27.26" *)
  reg [2:0] addr_V_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:1.18-1.24" *)
  input ap_clk;
  wire ap_clk;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:1.32-1.38" *)
  input ap_rst;
  wire ap_rst;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:11.15-11.23" *)
  wire [3:0] data_V_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:15.14-15.26" *)
  reg [3:0] data_V_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:22.15-22.23" *)
  wire [3:0] data_V_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:26.14-26.26" *)
  reg [3:0] data_V_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:9.9-9.14" *)
  wire eoc_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:13.8-13.17" *)
  reg eoc_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:20.9-20.14" *)
  wire eoc_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:24.8-24.17" *)
  reg eoc_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:10.9-10.15" *)
  wire memw_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:14.8-14.18" *)
  reg memw_1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:21.9-21.15" *)
  wire memw_2;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:25.8-25.18" *)
  reg memw_2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:3.24-3.29" *)
  input [2:0] num_V;
  wire [2:0] num_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:4.22-4.27" *)
  output [3:0] out_V;
  wire [3:0] out_V;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:5.16-5.28" *)
  output out_V_ap_vld;
  wire out_V_ap_vld;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:2.21-2.27" *)
  input [5:0] seed_V;
  wire [5:0] seed_V;
  (* hdlname = "u1 actnum_V_1_fu_64" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:52.13-52.29" *)
  reg [2:0] \u1.actnum_V_1_fu_64 ;
  (* hdlname = "u1 actnum_V_fu_217_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:53.14-53.32" *)
  wire [2:0] \u1.actnum_V_fu_217_p2 ;
  (* hdlname = "u1 add_ln214_fu_205_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:45.14-45.33" *)
  wire [5:0] \u1.add_ln214_fu_205_p2 ;
  (* hdlname = "u1 addr_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:35.15-35.21" *)
  wire [2:0] \u1.addr_V ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u1 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:40.41-40.50" *)
  reg [1:0] \u1.ap_CS_fsm  = 2'h1;
  (* hdlname = "u1 ap_CS_fsm_state1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:41.9-41.25" *)
  wire \u1.ap_CS_fsm_state1 ;
  (* hdlname = "u1 ap_CS_fsm_state2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:43.9-43.25" *)
  wire \u1.ap_CS_fsm_state2 ;
  (* hdlname = "u1 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:57.13-57.22" *)
  wire [1:0] \u1.ap_NS_fsm ;
  (* hdlname = "u1 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:27.9-27.15" *)
  wire \u1.ap_clk ;
  (* hdlname = "u1 ap_phi_mux_p_027_1_phi_fu_155_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:50.13-50.45" *)
  wire [3:0] \u1.ap_phi_mux_p_027_1_phi_fu_155_p4 ;
  (* hdlname = "u1 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:28.9-28.15" *)
  wire \u1.ap_rst ;
  (* hdlname = "u1 data_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:34.15-34.21" *)
  wire [3:0] \u1.data_V ;
  (* hdlname = "u1 eoc" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:32.10-32.13" *)
  wire \u1.eoc ;
  (* hdlname = "u1 flag_0_reg_141" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:49.13-49.27" *)
  reg \u1.flag_0_reg_141 ;
  (* hdlname = "u1 flag_fu_187_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:42.14-42.28" *)
  wire \u1.flag_fu_187_p2 ;
  (* hdlname = "u1 icmp_ln883_fu_172_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:44.14-44.34" *)
  wire \u1.icmp_ln883_fu_172_p2 ;
  (* hdlname = "u1 memw" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:33.10-33.14" *)
  wire \u1.memw ;
  (* hdlname = "u1 num_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:30.14-30.19" *)
  wire [2:0] \u1.num_V ;
  (* hdlname = "u1 p_027_0_reg_129" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:48.13-48.28" *)
  reg [3:0] \u1.p_027_0_reg_129 ;
  (* hdlname = "u1 seed_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:29.14-29.20" *)
  wire [5:0] \u1.seed_V ;
  (* hdlname = "u1 seed_V_read_assign_reg_120" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:47.13-47.39" *)
  reg [5:0] \u1.seed_V_read_assign_reg_120 ;
  (* hdlname = "u1 shl_ln214_fu_193_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:55.14-55.33" *)
  wire [5:0] \u1.shl_ln214_fu_193_p2 ;
  (* hdlname = "u1 sub_ln214_fu_199_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:56.14-56.33" *)
  wire [5:0] \u1.sub_ln214_fu_199_p2 ;
  (* hdlname = "u1 tmp_fu_177_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:54.14-54.27" *)
  wire [4:0] \u1.tmp_fu_177_p4 ;
  (* hdlname = "u1 vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:31.10-31.13" *)
  wire \u1.vld ;
  (* hdlname = "u1 width_V_fu_228_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:46.14-46.31" *)
  wire [3:0] \u1.width_V_fu_228_p2 ;
  (* hdlname = "u1 xor_ln53_fu_211_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:51.14-51.32" *)
  wire \u1.xor_ln53_fu_211_p2 ;
  (* hdlname = "u2 actnum_V_1_fu_74" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:53.13-53.29" *)
  reg [2:0] \u2.actnum_V_1_fu_74 ;
  (* hdlname = "u2 actnum_V_fu_227_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:54.14-54.32" *)
  wire [2:0] \u2.actnum_V_fu_227_p2 ;
  (* hdlname = "u2 add_ln214_fu_215_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:46.14-46.33" *)
  wire [5:0] \u2.add_ln214_fu_215_p2 ;
  (* hdlname = "u2 addr_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:36.15-36.21" *)
  wire [2:0] \u2.addr_V ;
  (* fsm_encoding = "none" *)
  (* hdlname = "u2 ap_CS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:41.41-41.50" *)
  reg [2:0] \u2.ap_CS_fsm  = 3'h1;
  (* hdlname = "u2 ap_CS_fsm_state1" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:42.9-42.25" *)
  wire \u2.ap_CS_fsm_state1 ;
  (* hdlname = "u2 ap_CS_fsm_state2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:44.9-44.25" *)
  wire \u2.ap_CS_fsm_state2 ;
  (* hdlname = "u2 ap_NS_fsm" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:58.13-58.22" *)
  wire [2:0] \u2.ap_NS_fsm ;
  (* hdlname = "u2 ap_clk" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:28.9-28.15" *)
  wire \u2.ap_clk ;
  (* hdlname = "u2 ap_phi_mux_p_027_1_phi_fu_165_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:51.13-51.45" *)
  wire [3:0] \u2.ap_phi_mux_p_027_1_phi_fu_165_p4 ;
  (* hdlname = "u2 ap_rst" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:29.9-29.15" *)
  wire \u2.ap_rst ;
  (* hdlname = "u2 data_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:35.15-35.21" *)
  wire [3:0] \u2.data_V ;
  (* hdlname = "u2 eoc" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:33.10-33.13" *)
  wire \u2.eoc ;
  (* hdlname = "u2 flag_0_reg_151" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:50.13-50.27" *)
  reg \u2.flag_0_reg_151 ;
  (* hdlname = "u2 flag_fu_197_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:43.14-43.28" *)
  wire \u2.flag_fu_197_p2 ;
  (* hdlname = "u2 icmp_ln883_fu_182_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:45.14-45.34" *)
  wire \u2.icmp_ln883_fu_182_p2 ;
  (* hdlname = "u2 memw" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:34.10-34.14" *)
  wire \u2.memw ;
  (* hdlname = "u2 num_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:31.14-31.19" *)
  wire [2:0] \u2.num_V ;
  (* hdlname = "u2 p_027_0_reg_139" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:49.13-49.28" *)
  reg [3:0] \u2.p_027_0_reg_139 ;
  (* hdlname = "u2 seed_V" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:30.14-30.20" *)
  wire [5:0] \u2.seed_V ;
  (* hdlname = "u2 seed_V_read_assign_reg_130" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:48.13-48.39" *)
  reg [5:0] \u2.seed_V_read_assign_reg_130 ;
  (* hdlname = "u2 shl_ln214_fu_203_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:56.14-56.33" *)
  wire [5:0] \u2.shl_ln214_fu_203_p2 ;
  (* hdlname = "u2 sub_ln214_fu_209_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:57.14-57.33" *)
  wire [5:0] \u2.sub_ln214_fu_209_p2 ;
  (* hdlname = "u2 tmp_1_fu_187_p4" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:55.14-55.29" *)
  wire [4:0] \u2.tmp_1_fu_187_p4 ;
  (* hdlname = "u2 vld" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:32.10-32.13" *)
  wire \u2.vld ;
  (* hdlname = "u2 width_V_fu_238_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:47.14-47.31" *)
  wire [3:0] \u2.width_V_fu_238_p2 ;
  (* hdlname = "u2 xor_ln53_fu_221_p2" *)
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:52.14-52.32" *)
  wire \u2.xor_ln53_fu_221_p2 ;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:7.8-7.14" *)
  reg v1_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:18.8-18.14" *)
  reg v2_buf;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:8.9-8.12" *)
  wire v_1;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:19.9-19.12" *)
  wire v_2;
  always @* if (1'h1) assert(_074_);
  assign _010_ = eoc_1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.47-71.68" *) eoc_2_buf;
  assign _011_ = memw_1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.72-71.94" *) memw_2_buf;
  assign _012_ = data_V_1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.98-71.124" *) data_V_2_buf;
  assign _013_ = addr_V_1_buf == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.128-71.154" *) addr_V_2_buf;
  assign \u1.actnum_V_fu_217_p2  = \u1.actnum_V_1_fu_64  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:160.30-160.53" *) 1'h1;
  assign \u1.add_ln214_fu_205_p2  = 1'h1 + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:162.31-162.57" *) \u1.sub_ln214_fu_199_p2 ;
  assign \u1.width_V_fu_228_p2  = \u1.ap_phi_mux_p_027_1_phi_fu_155_p4  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:184.29-184.68" *) 1'h1;
  assign _026_ = _030_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.49-135.110" *) _029_;
  assign _027_ = _026_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.49-135.139" *) \u1.ap_CS_fsm [1];
  assign _028_ = \u1.icmp_ln883_fu_172_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:148.18-148.77" *) \u1.ap_CS_fsm [1];
  assign _024_ = \u1.xor_ln53_fu_211_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:73.10-73.71" *) _029_;
  assign _025_ = _024_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:73.10-73.100" *) \u1.ap_CS_fsm [1];
  assign _023_ = _029_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:81.10-81.69" *) \u1.ap_CS_fsm [1];
  assign _029_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:105.11-105.39" *) \u1.icmp_ln883_fu_172_p2 ;
  assign _030_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.50-135.76" *) \u1.xor_ln53_fu_211_p2 ;
  assign _031_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:174.27-174.48" *) \u1.seed_V_read_assign_reg_120 [5:1];
  assign _032_ = \u1.actnum_V_1_fu_64  == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:176.33-176.58" *) \u1.num_V ;
  assign _033_ = \u1.ap_CS_fsm [0] | (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.19-135.140" *) _027_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:96.1-102.4" *)
  always @(posedge \u1.ap_clk )
    \u1.seed_V_read_assign_reg_120  <= _018_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:88.1-94.4" *)
  always @(posedge \u1.ap_clk )
    \u1.p_027_0_reg_129  <= _017_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:80.1-86.4" *)
  always @(posedge \u1.ap_clk )
    \u1.flag_0_reg_141  <= _016_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:72.1-78.4" *)
  always @(posedge \u1.ap_clk )
    \u1.actnum_V_1_fu_64  <= _014_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:64.1-70.4" *)
  always @(posedge \u1.ap_clk )
    \u1.ap_CS_fsm  <= _015_;
  assign _019_ = _028_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:148.13-152.16|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:148.17-148.78" *) 2'h1 : 2'h2;
  assign _034_ = \u1.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:143.5-157.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:0.0-0.0" *) 2'h2;
  function [1:0] _112_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    (* full_case = 32'd1 *)
    (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:143.5-157.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      2'b?1:
        _112_ = b[1:0];
      2'b1?:
        _112_ = b[3:2];
      default:
        _112_ = a;
    endcase
  endfunction
  assign \u1.ap_NS_fsm  = _112_(2'hx, { 2'h2, _019_ }, { _035_, _034_ });
  assign _035_ = \u1.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:143.5-157.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:0.0-0.0" *) 1'h1;
  assign _022_ = _033_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.14-139.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:135.18-135.141" *) 1'h0 : 1'hx;
  assign \u1.vld  = _025_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:133.5-139.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:133.9-133.101" *) 1'h1 : _022_;
  assign _021_ = \u1.xor_ln53_fu_211_p2  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:120.9-126.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:120.13-120.41" *) 1'h1 : 1'h0;
  assign \u1.memw  = _023_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:119.5-129.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:119.9-119.70" *) _021_ : 1'hx;
  assign _020_ = \u1.xor_ln53_fu_211_p2  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:106.9-112.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:106.13-106.41" *) 4'h0 : \u1.p_027_0_reg_129 ;
  assign \u1.ap_phi_mux_p_027_1_phi_fu_155_p4  = _023_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:105.5-115.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:105.9-105.70" *) _020_ : 4'hx;
  assign _036_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:99.14-101.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:99.18-99.44" *) \u1.seed_V  : \u1.seed_V_read_assign_reg_120 ;
  assign _018_ = _023_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:97.5-101.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:97.9-97.70" *) \u1.add_ln214_fu_205_p2  : _036_;
  assign _037_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:91.14-93.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:91.18-91.44" *) 4'h0 : \u1.p_027_0_reg_129 ;
  assign _017_ = _023_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:89.5-93.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:89.9-89.70" *) \u1.width_V_fu_228_p2  : _037_;
  assign _038_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:83.14-85.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:83.18-83.44" *) 1'h0 : \u1.flag_0_reg_141 ;
  assign _016_ = _023_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:81.5-85.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:81.9-81.70" *) \u1.flag_fu_187_p2  : _038_;
  assign _039_ = \u1.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:75.14-77.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:75.18-75.44" *) 3'h0 : \u1.actnum_V_1_fu_64 ;
  assign _014_ = _025_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:73.5-77.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:73.9-73.101" *) \u1.actnum_V_fu_217_p2  : _039_;
  assign _015_ = \u1.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:65.5-69.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:65.9-65.23" *) 2'h1 : \u1.ap_NS_fsm ;
  assign \u1.sub_ln214_fu_199_p2  = { \u1.seed_V_read_assign_reg_120 [2:0], 3'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:180.31-180.79" *) \u1.seed_V_read_assign_reg_120 ;
  assign \u1.flag_fu_187_p2  = _031_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:174.26-174.63" *) 1'h1 : 1'h0;
  assign \u1.icmp_ln883_fu_172_p2  = _032_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:176.32-176.73" *) 1'h1 : 1'h0;
  assign \u1.xor_ln53_fu_211_p2  = \u1.flag_fu_187_p2  ^ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:29.13-37.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1.v:186.30-186.61" *) \u1.flag_0_reg_141 ;
  assign \u2.actnum_V_fu_227_p2  = \u2.actnum_V_1_fu_74  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:164.30-164.53" *) 1'h1;
  assign \u2.add_ln214_fu_215_p2  = 1'h1 + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:166.31-166.57" *) \u2.sub_ln214_fu_209_p2 ;
  assign \u2.width_V_fu_238_p2  = \u2.ap_phi_mux_p_027_1_phi_fu_165_p4  + (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:188.29-188.68" *) 1'h1;
  assign _052_ = _055_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.49-136.110" *) _054_;
  assign _053_ = _052_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.49-136.139" *) \u2.ap_CS_fsm [1];
  assign _049_ = _054_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:149.18-149.77" *) \u2.ap_CS_fsm [1];
  assign _050_ = \u2.xor_ln53_fu_221_p2  & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:74.10-74.71" *) _054_;
  assign _051_ = _050_ & (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:74.10-74.100" *) \u2.ap_CS_fsm [1];
  assign _054_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:106.11-106.39" *) \u2.icmp_ln883_fu_182_p2 ;
  assign _055_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.50-136.76" *) \u2.xor_ln53_fu_221_p2 ;
  assign _056_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:178.27-178.50" *) \u2.seed_V_read_assign_reg_130 [5:1];
  assign _057_ = \u2.actnum_V_1_fu_74  == (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:180.33-180.58" *) \u2.num_V ;
  assign _058_ = \u2.ap_CS_fsm [0] | (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.19-136.140" *) _053_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:97.1-103.4" *)
  always @(posedge \u2.ap_clk )
    \u2.seed_V_read_assign_reg_130  <= _044_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:89.1-95.4" *)
  always @(posedge \u2.ap_clk )
    \u2.p_027_0_reg_139  <= _043_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:81.1-87.4" *)
  always @(posedge \u2.ap_clk )
    \u2.flag_0_reg_151  <= _042_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:73.1-79.4" *)
  always @(posedge \u2.ap_clk )
    \u2.actnum_V_1_fu_74  <= _040_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:65.1-71.4" *)
  always @(posedge \u2.ap_clk )
    \u2.ap_CS_fsm  <= _041_;
  assign _045_ = _049_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:149.13-153.16|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:149.17-149.78" *) 3'h2 : 3'h4;
  assign _059_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:144.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:0.0-0.0" *) 2'h2;
  function [2:0] _153_;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    (* full_case = 32'd1 *)
    (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:144.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:0.0-0.0" *)
    (* parallel_case *)
    casez (s)
      3'b??1:
        _153_ = b[2:0];
      3'b?1?:
        _153_ = b[5:3];
      3'b1??:
        _153_ = b[8:6];
      default:
        _153_ = a;
    endcase
  endfunction
  assign \u2.ap_NS_fsm  = _153_(3'hx, { 3'h2, _045_, 3'h1 }, { _061_, _059_, _060_ });
  assign _060_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:144.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:0.0-0.0" *) 3'h4;
  assign _061_ = \u2.ap_CS_fsm  == (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:144.5-161.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:0.0-0.0" *) 1'h1;
  assign _048_ = _058_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.14-140.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:136.18-136.141" *) 1'h0 : 1'hx;
  assign \u2.vld  = _051_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:134.5-140.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:134.9-134.101" *) 1'h1 : _048_;
  assign _047_ = \u2.xor_ln53_fu_221_p2  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:121.9-127.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:121.13-121.41" *) 1'h1 : 1'h0;
  assign \u2.memw  = _049_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:120.5-130.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:120.9-120.70" *) _047_ : 1'hx;
  assign _046_ = \u2.xor_ln53_fu_221_p2  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:107.9-113.12|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:107.13-107.41" *) 4'h0 : \u2.p_027_0_reg_139 ;
  assign \u2.ap_phi_mux_p_027_1_phi_fu_165_p4  = _049_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:106.5-116.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:106.9-106.70" *) _046_ : 4'hx;
  assign _062_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:100.14-102.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:100.18-100.44" *) \u2.seed_V  : \u2.seed_V_read_assign_reg_130 ;
  assign _044_ = _049_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:98.5-102.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:98.9-98.70" *) \u2.add_ln214_fu_215_p2  : _062_;
  assign _063_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:92.14-94.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:92.18-92.44" *) 4'h0 : \u2.p_027_0_reg_139 ;
  assign _043_ = _049_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:90.5-94.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:90.9-90.70" *) \u2.width_V_fu_238_p2  : _063_;
  assign _064_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:84.14-86.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:84.18-84.44" *) 1'h0 : \u2.flag_0_reg_151 ;
  assign _042_ = _049_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:82.5-86.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:82.9-82.70" *) \u2.flag_fu_197_p2  : _064_;
  assign _065_ = \u2.ap_CS_fsm [0] ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:76.14-78.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:76.18-76.44" *) 3'h0 : \u2.actnum_V_1_fu_74 ;
  assign _040_ = _051_ ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:74.5-78.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:74.9-74.101" *) \u2.actnum_V_fu_227_p2  : _065_;
  assign _041_ = \u2.ap_rst  ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:66.5-70.8|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:66.9-66.23" *) 3'h1 : \u2.ap_NS_fsm ;
  assign \u2.sub_ln214_fu_209_p2  = { \u2.seed_V_read_assign_reg_130 [2:0], 3'h0 } - (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:184.31-184.79" *) \u2.seed_V_read_assign_reg_130 ;
  assign \u2.flag_fu_197_p2  = _056_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:178.26-178.65" *) 1'h1 : 1'h0;
  assign \u2.icmp_ln883_fu_182_p2  = _057_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:180.32-180.73" *) 1'h1 : 1'h0;
  assign \u2.xor_ln53_fu_221_p2  = \u2.flag_fu_197_p2  ^ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:39.15-47.23|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/barcode_1_1.v:190.30-190.61" *) \u2.flag_0_reg_151 ;
  assign _066_ = v_1 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.12-54.26" *) _072_;
  assign _067_ = v_2 && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.12-61.26" *) _073_;
  assign _068_ = v1_buf && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.24-71.40" *) v2_buf;
  assign _069_ = _010_ && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.46-71.95" *) _011_;
  assign _070_ = _069_ && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.46-71.125" *) _012_;
  assign _071_ = _070_ && (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.46-71.155" *) _013_;
  assign _072_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.19-54.26" *) v1_buf;
  assign _073_ = ! (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.19-61.26" *) v2_buf;
  assign _074_ = _075_ || (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.22-71.156" *) _071_;
  assign _075_ = ~ (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:71.22-71.41" *) _068_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    v1_buf <= _008_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    eoc_1_buf <= _004_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    memw_1_buf <= _006_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    data_V_1_buf <= _002_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    addr_V_1_buf <= _000_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    v2_buf <= _009_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    eoc_2_buf <= _005_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    memw_2_buf <= _007_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    data_V_2_buf <= _003_;
  (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:49.4-69.7" *)
  always @(posedge ap_clk)
    addr_V_2_buf <= _001_;
  assign _076_ = _067_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.12-61.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.8-67.11" *) addr_V_2 : addr_V_2_buf;
  assign _001_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) addr_V_2_buf : _076_;
  assign _077_ = _067_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.12-61.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.8-67.11" *) data_V_2 : data_V_2_buf;
  assign _003_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) data_V_2_buf : _077_;
  assign _078_ = _067_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.12-61.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.8-67.11" *) memw_2 : memw_2_buf;
  assign _007_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) memw_2_buf : _078_;
  assign _079_ = _067_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.12-61.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.8-67.11" *) eoc_2 : eoc_2_buf;
  assign _005_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) eoc_2_buf : _079_;
  assign _080_ = _067_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.12-61.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:61.8-67.11" *) 1'h1 : v2_buf;
  assign _009_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) 1'h0 : _080_;
  assign _081_ = _066_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.12-54.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.8-60.11" *) addr_V_1 : addr_V_1_buf;
  assign _000_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) addr_V_1_buf : _081_;
  assign _082_ = _066_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.12-54.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.8-60.11" *) data_V_1 : data_V_1_buf;
  assign _002_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) data_V_1_buf : _082_;
  assign _083_ = _066_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.12-54.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.8-60.11" *) memw_1 : memw_1_buf;
  assign _006_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) memw_1_buf : _083_;
  assign _084_ = _066_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.12-54.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.8-60.11" *) eoc_1 : eoc_1_buf;
  assign _004_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) eoc_1_buf : _084_;
  assign _085_ = _066_ ? (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.12-54.26|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:54.8-60.11" *) 1'h1 : v1_buf;
  assign _008_ = ap_rst ? (* full_case = 32'd1 *) (* src = "/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.9-50.15|/data/zhiyuany/property_mining/seq_dreamminer/barcode_wrapper1_1/top.v:50.6-68.9" *) 1'h0 : _085_;
  assign \u2.addr_V  = \u2.actnum_V_1_fu_74 ;
  assign \u2.ap_CS_fsm_state1  = \u2.ap_CS_fsm [0];
  assign \u2.ap_CS_fsm_state2  = \u2.ap_CS_fsm [1];
  assign \u2.data_V  = \u2.p_027_0_reg_139 ;
  assign \u2.eoc  = 1'h0;
  assign \u2.shl_ln214_fu_203_p2  = { \u2.seed_V_read_assign_reg_130 [2:0], 3'h0 };
  assign \u2.tmp_1_fu_187_p4  = \u2.seed_V_read_assign_reg_130 [5:1];
  assign addr_V_2 = \u2.addr_V ;
  assign \u2.ap_clk  = ap_clk;
  assign \u2.ap_rst  = ap_rst;
  assign data_V_2 = \u2.data_V ;
  assign eoc_2 = \u2.eoc ;
  assign memw_2 = \u2.memw ;
  assign \u2.num_V  = num_V;
  assign \u2.seed_V  = seed_V;
  assign v_2 = \u2.vld ;
  assign \u1.addr_V  = \u1.actnum_V_1_fu_64 ;
  assign \u1.ap_CS_fsm_state1  = \u1.ap_CS_fsm [0];
  assign \u1.ap_CS_fsm_state2  = \u1.ap_CS_fsm [1];
  assign \u1.data_V  = \u1.p_027_0_reg_129 ;
  assign \u1.eoc  = 1'h0;
  assign \u1.shl_ln214_fu_193_p2  = { \u1.seed_V_read_assign_reg_120 [2:0], 3'h0 };
  assign \u1.tmp_fu_177_p4  = \u1.seed_V_read_assign_reg_120 [5:1];
  assign addr_V_1 = \u1.addr_V ;
  assign \u1.ap_clk  = ap_clk;
  assign \u1.ap_rst  = ap_rst;
  assign data_V_1 = \u1.data_V ;
  assign eoc_1 = \u1.eoc ;
  assign memw_1 = \u1.memw ;
  assign \u1.num_V  = num_V;
  assign \u1.seed_V  = seed_V;
  assign v_1 = \u1.vld ;
endmodule
